### ISSUE TITLE
UglifyJS warnings

### ISSUE THREAD

**Issue by ayozebarrera** [Pomax/react-onclickoutside#101]
Hi, there are some warnings in your code:

```
Condition always true [./~/react-onclickoutside/index.js:16,0]
Dropping unreachable code [./~/react-onclickoutside/index.js:21,3]
```

**Comment by Pomax** [comment]
is that on the latest version? those line numbers don't seem to line up with the current [index.js](https://github.com/Pomax/react-onclickoutside/blob/master/index.js)...

**Comment by Pomax** [comment]
closing as this feels related to an older version, but if this is still the case for v5.x (5.3 as of this comment) please feel free to counter-comment with steps to reproduce, or opening a new issue with those STR.
