### ISSUE TITLE
Scope is not the correct one?

### ISSUE THREAD

**Issue by FezVrasta** [Pomax/react-onclickoutside#103]
I have this little component:

```
class Foobar extends React.Component {
  render() {
    return <div ref={e => ( this.element = e )}></div>;
  }
  handleClickOutside(evt) {
    console.log(this.element);
  }
}
```

I have two of those components inside my page, but both of them returns the `element` of the last inserted one instead of keeping the one relative to the current component instance.

What happens?

**Comment by Pomax** [comment]
I'm not sure I understand; given this Foobar code, can you also show the rest of what you're doing? (e.g. `export default hocwrapped(Foobar)`, the code where you actually use those in your app, etc?).

**Comment by Pomax** [comment]
@FezVrasta heya, is this still an issue for you? If so, can you add an [mcve](https://stackoverflow.com/help/mcve) that demonstrates this so that I (or other contributors!) can see why this might be happening?
