### ISSUE TITLE
handleClickOutside not working in ReactTestUtils

### ISSUE THREAD

**Issue by bdwain** [Pomax/react-onclickoutside#104]
I'm trying to test that clicking outside my component executes the behavior that i specified, but it doesn't seem to recognize the simulated click event from react test utils (I'm using 15.1.0) (it works fine in actual normal usage)

```javascript
it('closes the section when clicking outside of the component', function(){
   let wrapper = ReactTestUtils.renderIntoDocument(
      <TestWrapper>
        <div className="foo">hello</div>
        <WrappedComponent />
      </TestWrapper>);

   let toggleBtn = ReactTestUtils.findRenderedDOMComponentWithClass(wrapper, 'toggleBtn');
   ReactTestUtils.Simulate.click(toggleBtn); //open

   let fooDiv = ReactTestUtils.findRenderedDOMComponentWithClass(wrapper, 'foo');
   ReactTestUtils.Simulate.click(fooDiv); //close
   let elementsThatShouldBeGone = ReactTestUtils.scryRenderedDOMComponentWithClass(wrapper, 'toggled-element');
   expect(elementsThatShouldBeGone.length).toBe(0); //fail. it's 1
});

//simple wrapper to allow for searching with react test utils
class TestWrapper extends React.Component{
  constructor(props){
    super(props);
  }

  render(){
    return <div>{this.props.children}</div>;
  }
}
```

Any ideas what might be going wrong? It just doesn't call handleClickOutside at all when i click on foo. Clicking works in general. If i change the final click to click on the toggle button again, it runs the close functionality as expected. It's just clicking on foo that does nothing.

**Comment by rafeememon** [comment]
FWIW, I had a heck of a time trying to get this to work in #75, and I eventually ended up giving up =(

**Comment by bdwain** [comment]
ah really? so simulated events just dont work? only real events? well that's good to know. thanks.

**Comment by Pomax** [comment]
I've never used the TestUtils (only ever used Mocha/Phantom, which is literally a browser instead of trying to simulate one) so this *might* be worth asking the facebook crew about?

**Comment by bdwain** [comment]
@Pomax the testutils aren't a browser replacement. My tests also run in phantom/jasmine. The test utils are just tools to help test your component in isolation and traverse the virtual dom. 

Either way though, i tried testing the way @rafeememon mentioned in #75 with the mousedown event and it worked. 

I'm confused why it doesn't work if I use a click event instead of a mousedown event on the document. 

`document.dispatchEvent(new Event('click')); //fails`

also, i feel like this specifically should work

```javascript
//a sibling to firstElementChild has the onclickoutside wrapper
javascriptReactDOM.findDOMNode(wrapper).firstElementChild.dispatchEvent(new Event('click'));
``` 

but also doesn't

**Comment by Pomax** [comment]
"click" and "mousedown" are technically different events, when you issue a click through the TestUtils, does it also fire the `mousedown` and `mouseup` events as an HID like a mouse or tablet would,  or does it *just* fire the `mouseclick` event? Because that might be the difference.

**Comment by bdwain** [comment]
oh i didn't realize it explicitly listened for mousedown events. that makes sense then. i'll see if i can simulate that

**Comment by bdwain** [comment]
`ReactTestUtils.Simulate.mouseDown(ReactTestUtils.findRenderedDOMComponentWithClass(wrapper, 'foo'));`

That didn't work. However, I'm realizing that the code is using document.addEventListener, and not react's onMouseDown or whatever handler, so it probably makes sense that the simulated events don't get caught. Since it's not listening to virtual dom events. 

Thinking about how this would work, i'd imagine that that's unavoidable. so i'll close this for now.

**Comment by Pomax** [comment]
yeah, since we listening for events *outside* of the React component, there is no nice virtual DOM event that we can listen for, we instead need to listen for DOM events in "everything that isn't this component", which means plain DOM events based on the active document.
