### ISSUE TITLE
Version 5.3.1 issue

### ISSUE THREAD

**Issue by natejstar** [Pomax/react-onclickoutside#111]
I just upgraded to 5.3.1 from 5.2.0.

the function that starts with
```javascript
handleClickOutside(event) { ... }
```
was giving an error that event is undefined in 5.3.1. I reverted back to 5.2.0 and I'm good to go again.

**Comment by rafeememon** [comment]
Related to #102 and #110?

**Comment by Pomax** [comment]
v5.3.2 pushed to npm, which should fix things for now.
