### ISSUE TITLE
Add support for config, allow users to specify onClickOutside handler

### ISSUE THREAD

**Issue by no23reason** [Pomax/react-onclickoutside#115]
Add the support of configuration of the HOC. The most apparent setting is to allow the users to specify which method of their components should be called when the click outside happens. The reason for this is that it removes the implicit dependency on the `handleClickOutside` method. This means that if my component does not have this method, the error is manifested at runtime, whereas if I explicitly specify the handler, the error can be detected in compile-time (e.g. when using TypeScript). For more on implicit dependencies I recommend this [article on mixins and HOC's](https://facebook.github.io/react/blog/2016/07/13/mixins-considered-harmful.html).

The support for config would also allow to introduce more configuration options or moving some configuration from props to config (e.g. `eventTypes`) in the future.

**Comment by Pomax** [comment]
moving the error to compile-time rather than run-time certainly sounds like a valuable improvement
