### ISSUE TITLE
Stateless component causes errors trying to read refs

### ISSUE THREAD

**Issue by davishmcclurg** [Pomax/react-onclickoutside#127]
Related: https://github.com/Pomax/react-onclickoutside/issues/98

Stateless component support was recently added, but seems to be broken. I tested this with a simple react app (I mostly wanted to try out Create React App): https://github.com/davishmcclurg/react-onclickoutside-issue

The stateless component is defined here: https://github.com/davishmcclurg/react-onclickoutside-issue/blob/master/src/App.js

This is what I see in the console:

> Warning: Stateless function components cannot be given refs (See ref "instance" in StatelessComponent created by OnClickOutside(Component)). Attempts to access this ref will fail.

And:

> Uncaught TypeError: Cannot read property 'handleClickOutside' of null

**Comment by Pomax** [comment]
Hmm, this does not appear to be a true stateless component, which is just a
```
var MyStatelessComponent = function (props) {
  return <div>
    <p>whatever you need here with {this.props.data} worked in</p>
  </div>;
};
```

Instead this seems more like a full React component with props and state, but for which the state is never initialised or used.

That doesn't make it less of a bug, but it does change when people will run into this.

**Comment by Pomax** [comment]
v5.6.0 just got released which might fix the problem - would you be willing to test and see if that invalidates this issue?

**Comment by davishmcclurg** [comment]
@Pomax the stateless component is actually here: https://github.com/davishmcclurg/react-onclickoutside-issue/blob/master/src/App.js#L8

It's passed as an anonymous function to onClickOutside.

I'll test the new version now.

**Comment by davishmcclurg** [comment]
Upgrading didn't fix the issue.

**Comment by Pomax** [comment]
hm, without refs there is no way to actually gain access to the underlying instance, the HOC would somehow have to tap into the UI that gets returned by the render function instead... This will need a bit of process and design thinking... =(
