### ISSUE TITLE
A Lot of Static Elements

### ISSUE THREAD

**Issue by ChiefORZ** [Pomax/react-onclickoutside#13]
Hey,

Just out of curiosity, thnk of a Page with lots of Components - which are all Mounted already.
Every single Component uses one Mixin wheter i clicked outside a Dropdown - or not...

For each single Mouseclick on the Page, each Event is emitted and therefore every Function from those Child Components is executed - correct me if i'm wrong...

Wouldn't it be more efficient - memory wise - to attach the Event, only when i need it?

**Comment by Pomax** [comment]
if that's your usecase, then certainly. There's no listen/ignore flag right now, so if you want to turn this into a feature request instead of just a question: cool. If you want to try your hand at writing that in as a PR: also cool

**Comment by Pomax** [comment]
actually, added this in and published as v0.2.4 -- have a look at the updated README.md.
