### ISSUE TITLE
Add a class to treat an inside click like an outside click

### ISSUE THREAD

**Issue by Tenga** [Pomax/react-onclickoutside#132]
This would be somewhat of a reverse ignore (include?) feature.

Sometimes it is necessary to treat an element inside the component enhanced with onClickOutside as if it was an outside click.

**Comment by Pomax** [comment]
Can you explain your use case?

**Comment by seleckis** [comment]
@Tenga I think you have to add `onClick` handle for that element and trigger appropriate method. That would be more logical, than some `include` option.

**Comment by Tenga** [comment]
@Pomax My usecases were mostly things that I didn't really think through that evening, close/collapse on action clicks nested into multiple components.

@seleckis I agree, I'm closing this.
