### ISSUE TITLE
Fails completely if rendering into an environment without a DOM

### ISSUE THREAD

**Issue by dariusriggins** [Pomax/react-onclickoutside#136]
I'm adding snapshot testing from storyshots (conceptually from Jest) which is failing due to not being in an environment with a DOM. In my instance it's failing because `ReactDOM.findDOMNode is not a function` inside of `componentDidMount`.

While I don't expect this to _work_ in a non-DOM environment I would expect that it wouldn't fail and break my tests if in an environment it doesn't understand.

**Comment by Pomax** [comment]
why not? As a very specifically DOM-grounded hoc, that's one thing I absolutely would expect. PRs welcome to fix that, but expecting it to work without a DOM from the outset doesn't jive =)

**Comment by dariusriggins** [comment]
Yeah it's not ideal, but right now my only way to have tests is to conditionally wrap my component in the hoc if I'm running tests, which feels kinda hacky. 

And again, I don't expect it to functionally work, I would just like some manner to prevent it from a hard failure in that scenario. I'd imagine shallow rendering with testutils or Enzyme would also encounter the same thing.

**Comment by dariusriggins** [comment]
Cool, if you're fine with a try/catch or check for it then I'm happy to put together a PR.

**Comment by Pomax** [comment]
yeah that's fine by me, or even an `if (!ReactDOM.findDOMNode) { return early  }`. As long as it does not impair the code from doing what it needs to do when there is a dom to work with, I'm open to solutions.

**Comment by Pomax** [comment]
if that's the only way we can be sure we don't have a DOM, then that sounds fine - I'm a proponent of "solve a problem, then refine the approach when someone runs into edge cases with the solution"

**Comment by Pomax** [comment]
v5.7.1 released
