### ISSUE TITLE
IE11 - SVGSVGElement missing classList

### ISSUE THREAD

**Issue by elsassph** [Pomax/react-onclickoutside#142]
We've hit a NPE on IE11 with inline SVG:

     SCRIPT5007: Unable to get property 'contains' of undefined or null reference

It turned out `isNodeFound` is testing CSS classes on a `SVGSVGElement` which, as per Microsoft documentation, doesn't have a `classList` property: 

- https://msdn.microsoft.com/en-us/library/ff972122(v=vs.85).aspx

**Comment by rafeememon** [comment]
See the readme: https://github.com/Pomax/react-onclickoutside#ie-does-not-support-classlist-for-svg-elements

**Comment by Pomax** [comment]
as per @rafeememon, you have the power to fix this yourself. Don't ask modern libraries to shim old browser incompletions, just load the shims you need first and *every* library will work.
