### ISSUE TITLE
getDOMNode is deprecated

### ISSUE THREAD

**Issue by gabor** [Pomax/react-onclickoutside#15]
the code seems to use getDOMNode, and it has been deprecated in react:
https://facebook.github.io/react/docs/component-api.html#getdomnode

**Comment by Pomax** [comment]
good point. I'll try to do that sometime today, although if you want to file a PR because you had to fix this for your own project already, also cool =)

**Comment by crisberrios** [comment]
also related to this, the mixin does not work with React es6 classes (babel) + react-mixin.

**Comment by Pomax** [comment]
yeah, this code is currently incompatible with the native ES6 `class` concept, pretty much until React itself figures out how they actually want this to work.

**Comment by Pomax** [comment]
fixed in 0.2.5
