### ISSUE TITLE
Subtle API for disableOnClickOutside

### ISSUE THREAD

**Issue by vansosnin** [Pomax/react-onclickoutside#150]
Hello!
I have noticed that you have some strange API for `disableOnClickOutside`. [Here](https://github.com/Pomax/react-onclickoutside/blob/c215630e8a14fb7e5cd3d11401907b64fe8c3212/index.js#L182-L184) you check if `disableOnClickOutside` (which is actually should be a function)  is `true`, then do not enable listener.
This becomes confusing when I in my child component want to enable/disable listener. Here is some code:

```javascript
        if (disableOnClickOutside !== true) { // Here is already a function, even in construct()
            if (isOpen) {
                enableOnClickOutside();
            } else {
                disableOnClickOutside();
            }
        }
```

I mean, I want to pass some props to always disable listener, but also I have some inner logic to enable/disable listener.

I propose to pass some another props to disable initial `enableOnClickOutside`. Something like this:

```javascript
          // to save backward-compatibility
          if (!this.props.disableOnClickOutside || !this.props.disableInit) {
              this.enableOnClickOutside();
          }
```

If you are aggree with my proposal, I can do a pull-request.

**Comment by Pomax** [comment]
I don't understand, there is no `if (disableOnClickOutside !== true)` anywhere in the HOC code. Can you point to the actual lines of code in index.js?

**Comment by vansosnin** [comment]
There is a link: https://github.com/Pomax/react-onclickoutside/blob/c215630e8a14fb7e5cd3d11401907b64fe8c3212/index.js#L182-L184

That example of the code is in my child component.

**Comment by Pomax** [comment]
Your child component should not know anything about whether it is listening for clicks or not. It is wrapped by a higher order component, and awareness of "who listens for what" stops at the HOC, it should not go deeper.

Can you explain what you are trying to make your child do that makes you think it, rather than the parent, should determine whether the HOC listens for clicks or not?

**Comment by vansosnin** [comment]
For example, I have a _Popup_ component. It is wrapped by _react-onclickoutside_. In some cases I want to close my _Popup_ when I click outside, in other cases I don't want to close it.

For now it seems easy, I just can pass to it `disableOnClickOutside=true` and it's done.

Let's go further. I do not want to listen outside clicks when the _Popup_ is closed. Reason for this is that inside `handleClickOutside()` I call some callback, which (above the _Popup_) changes state of my application. So I have to write some check like this:

```javascript
if (isOpen) {
    enableOnClickOutside();
} else {
    disableOnClickOutside();
}
```

Am I right?

But I do not want to get to this check if I want to disable clickoutside from the beginning. So I want to wrap it more like this:

```javascript
if (disableOnClickOutside !== true) { // Not working: here is already a function
    if (isOpen) {
        enableOnClickOutside();
    } else {
        disableOnClickOutside();
    }
}
```

**Comment by Pomax** [comment]
You lose me at "I do not want to listen outside clicks when the Popup is closed", can you explain what you mean with that? In a properly written React application, "closing" the popup means the parent component removes it from the rendered DOM, the `<Popup>` unmounts, and the `onClickOutside` behaviour gets removed as part of the `componentWillUnmount` lifecycle hook in the HOC. As such, once the Popup closes, the HOC is no longer in effect, so I don't understand why "listening to outside clicks" is even still relevant at that point: the Popup should be gone.

**Comment by vansosnin** [comment]
I think you are right.
I just had a problem before React in some legacy jquery code, when you handle popup opening by click on button or something. Then I decided that it would be easier just to pass some _target_ to popup, and use it to open the popup. So habitually I decided to implement the same logic in React popup.
Thank you.
