### ISSUE TITLE
dist/release version

### ISSUE THREAD

**Issue by omouse** [Pomax/react-onclickoutside#155]
it'd be nice if the library was already built into dist/release

**Comment by Pomax** [comment]
why? there is no build, index.js is already the final library.

**Comment by omouse** [comment]
Oh, I wasn't aware of that. I thought the convention for frontend projects was to have release builds in dist (it may be a bit silly to do in this case).

**Comment by Pomax** [comment]
Ah, I see. Yeah not really: as long as the package.json `main` value points to the right file, that's all you need. `import` (ES6+) and `require` (Node) statements will then both work just fine.
