### ISSUE TITLE
Throws an error when clicking on an SVGElement in Safari

### ISSUE THREAD

**Issue by nikovanmeurs** [Pomax/react-onclickoutside#16]
The click handler throws an error when clicking on an SVGElement in Safari because it cannot call classList.contains on undefined.
This error is caused because SVGElements do not have a classList property in Safari.

### Proposed solution:

Check if source.classList is defined before executing source.classList.contains(IGNORE_CLASS)

**Comment by Pomax** [comment]
that's a workaround, not a real solution. Does Safari not support classList at all, or merely not on svg? Because that determines the code necessary to fix this properly. Also, which Safari are you finding this on (desktop vs. iOS)?

**Comment by nikovanmeurs** [comment]
Safari properly supports classList on HTML elements, just not on svg elements.
I haven't checked iOS yet, but the issue is present in all Safari desktop versions.

**Comment by Pomax** [comment]
webkit claims this was [resolved:fixed](https://bugs.webkit.org/show_bug.cgi?id=93014) in build 528+, I built a quick jsbin to test classList support over on http://jsbin.com/pesolerose/edit?html,js,output and will have a look what I see on my mac. If this is still broken, that needs to be reopened on the webkit bug tracker at least, and the PR will have to not just stop the code from erroring, but also actually do the right thing by looking at the classes probably without using classList =)

**Comment by Pomax** [comment]
`.classlist` for SVG works just fine in Safari 7.1 in OSX, as well as on an iPhone running iOS 8.4 (both report `testclass: true`), so I'm closing this issue.
