### ISSUE TITLE
create-react-class library is missing

### ISSUE THREAD

**Issue by jebarjonet** [Pomax/react-onclickoutside#165]
@Pomax Since https://github.com/Pomax/react-onclickoutside/pull/164 the lib seems broken.

```
ERROR in ./~/react-onclickoutside/index.js
Module not found: Error: Cannot resolve module 'create-react-class' in /home/app/node_modules/react-onclickoutside
 @ ./~/react-onclickoutside/index.js 290:6-293:8
```

`create-react-class` is only present in `devDependencies`

Has been reported here too https://github.com/storybooks/storybook-addon-knobs/issues/97

**Comment by hasancc** [comment]
+1 This has broken our build too.

**Comment by cs45977** [comment]
+1

**Comment by VinceRao** [comment]
+1

**Comment by dimitropoulos** [comment]
+1 another broken build because of this

**Comment by xuexb** [comment]
+1

**Comment by arvinsim** [comment]
+1

**Comment by Pomax** [comment]
dear all: I'm deleting these nonsense "+1" comments, there's literally a +1 button, use it =)

I'll also update the `package.json` to move `create-react-class` to the regular dependency list. Thanks for filing @jebarjonet

**Comment by Pomax** [comment]
v5.11.1 has been pushed to npm with the `create-react-class` as plain dependency.
