### ISSUE TITLE
Property 'disableOnClickOutside' is missing in type

### ISSUE THREAD

**Issue by engineersamuel** [Pomax/react-onclickoutside#171]
I am on the latest version of react-onclickoutside.  I have my HOC component also wrapped in another HOC, I previously was not having errors, something changed, which I am unsure what it is, however now I have the following error:

```
[at-loader] ./app/components/case/knowledgeResources/creation/FooBarEditPopover.tsx:211:69
    TS2345: Argument of type 'typeof FooBarEditPopoverLocal' is not assignable to parameter of type 'ComponentClass<IReduxProps & IOwnProps & InjectedOnClickOutProps & HandleClickOutside<any>> | Sta...'.
  Type 'typeof FooBarEditPopoverLocal' is not assignable to type 'ClickOutComponentClass<IReduxProps & IOwnProps & InjectedOnClickOutProps>'.
    Type 'FooBarEditPopoverLocal' is not assignable to type 'Component<IReduxProps & IOwnProps & InjectedOnClickOutProps, ComponentState> & HandleClickOutside...'.
      Type 'FooBarEditPopoverLocal' is not assignable to type 'Component<IReduxProps & IOwnProps & InjectedOnClickOutProps, ComponentState>'.
        Types of property 'props' are incompatible.
          Type 'Readonly<{ children?: ReactNode; }> & Readonly<IProps>' is not assignable to type 'Readonly<{ children?: ReactNode; }> & Readonly<IReduxProps & IOwnProps & InjectedOnClickOutProps>'.
            Type 'Readonly<{ children?: ReactNode; }> & Readonly<IProps>' is not assignable to type 'Readonly<IReduxProps & IOwnProps & InjectedOnClickOutProps>'.
              Property 'disableOnClickOutside' is missing in type 'Readonly<{ children?: ReactNode; }> & Readonly<IProps>'.
```
Previously I never needed to directly define `disableOnClickOutside` and `enableOnClickOutside`, yet now Typescript is claiming they need to be passed.

The HOCs look like:

```
const DraggableText = DragSource(DraggableTypes.FOO, draggableTextSpec, collect)(onClickOutside(DraggableTextLocal)) as React.ComponentClass<IOwnProps>;
export default DraggableText;
```

Where the error here is specifically on `onClickOutside(DraggableTextLocal)`.  Now if I directly define the `disableOnClickOutside` and `enableOnClickOutside`on the `DraggableTextLocal` it does resolve that error, however it now forces me to define those props in JSX where that shouldn't be necessary.

- Is this purely a Typescript issue?  I will note this doesn't appear to affect functionality.  Maybe the TS def files should have those two `disableOnClickOutside` and `enableOnClickOutside` as optional parameters?

- Should those props be defined in whatever Component `onClickOutside(Component)` is referencing?

The HOC `OnClickOut` contains:

```
    interface InjectedOnClickOutProps {
        disableOnClickOutside(): void;
        enableOnClickOutside(): void;
    }
```

And then:

`component: ComponentConstructor<P & OnClickOut.InjectedOnClickOutProps & OnClickOut.HandleClickOutside<any>>
        | ClickOutComponentClass<P & OnClickOut.InjectedOnClickOutProps>`

Which appears to indicate the disable/enable must be present and passed down.  https://github.com/Pomax/react-onclickoutside/issues/106 appeared to have resolved some issues surrounding this, so maybe this is just a TS def issue?  I can't quite tell and need ya'lls opinion as the developers of this lib.

**Comment by rafeememon** [comment]
Looks like a recent update to the types broke this: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/0d96c339bccb58d2f37181411438ddb403c08f70  I'd file an issue at DefiniteltyTyped.

**Comment by Pomax** [comment]
@engineersamuel can you reproduce this on minimal verifiable code example that uses this HOC in isolation?

**Comment by engineersamuel** [comment]
@rafeememon Brilliant, that was the issue, I downgraded one point version and that fixed it.  The point version lower has those props as optional.  Closing this.

**Comment by patreu22** [comment]
@engineersamuel Did anybody follow up on that? I'm still running into the same error :(

**Comment by engineersamuel** [comment]
@patreu22 I haven't attempted to re-upgrade to see if there is a new version of the @types that would fix this, but since you are still encountering this it sounds like it isn't fixed.

**Comment by flaurida** [comment]
I am also experiencing this. What would the steps to fix it entail?

**Comment by nicolashahn** [comment]
@patreu22 @engineersamuel @flaurida I opened a PR to make them optional again, but the author explained to me how it was supposed to work. See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22838#discussion_r161130863 for my fix

**Comment by ecrofeg** [comment]
@nicolashahn Thank you, mate :) I spent hours digging around to find out what's going on there..
