### ISSUE TITLE
The Click Listener seems to intercept clicks INSIDE the wrapped component

### ISSUE THREAD

**Issue by dhassouni** [Pomax/react-onclickoutside#173]
I am using onClickOutside to wrap a component with an input field in it. However, I am unable to click an arbitrary point in the text to edit, nor highlight the input field contents when wrapped with onClickOutside. Any suggested solutions?

**Comment by dhassouni** [comment]
FYI, my versions of react and react-onclickoutside from package.json
    "react": "15.3.2",
    "react-onclickoutside": "^5.11.1",

**Comment by Pomax** [comment]
Do you have an example that demonstrates this?

**Comment by dhassouni** [comment]
I made a simpler case to test it out, and of course, it works. I'm fairly certain what was going on was some bad interaction between another HOC that was wrapping the component as well. I think this case can be closes as my fiddle works fine:
https://jsfiddle.net/dhassouni/z85j45c9/2/
