### ISSUE TITLE
Marking elements as "consider only this one" during the event loop - Feature

### ISSUE THREAD

**Issue by David-Neto** [Pomax/react-onclickoutside#174]
Ok, here is something I thought would be really useful, the opposite of outside click ignore class. Only when clicking on a certain class, the event is triggered. Description adapted from documentation could be something like:
"If you want the HOC to consider only certain elements, you can tell the HOC which CSS class name it should use for this purposes. If you want explicit control over the class name, use outsideClickConsiderOnlyClass={some string} as component property."

**Comment by Pomax** [comment]
That's just standard event listening. You don't even need react for that, this is covered by base JS alone: add a listener to `document` that checks `evt.target.classList.contains("...")` and if so, does whatever needs to be done.
