### ISSUE TITLE
IE Bug: Clicking on svg causes error

### ISSUE THREAD

**Issue by blainekasten** [Pomax/react-onclickoutside#181]
This line is erroring out:
https://github.com/Pomax/react-onclickoutside/blob/master/src/generateOutsideCheck.js#L17

The cause appears that in IE11, SVGPathElement does not contain a classList property. Therefore calling contains on it errors out.

**Comment by rafeememon** [comment]
https://github.com/Pomax/react-onclickoutside#ie-does-not-support-classlist-for-svg-elements

**Comment by Pomax** [comment]
you'll have to shim IE so that it supports the modern web. Please see the abovementioned reademe for a link to a good shim that solves this problem and others for you.

**Comment by blainekasten** [comment]
Fair enough, thanks!

**Comment by amakhrov** [comment]
@Pomax Looks like you're only using classList in one place to check if the class list contains a specified class. It doesn't looks like a strong enough reason to drop support of IE11.
Would you consider a PR, which introduces a fallback to the classList shim (from the dom4 library)?

**Comment by Pomax** [comment]
no, I will not. What you're not seeing is the fact that this is an IE problem, not a "this library" problem. If your site relies on quirks in IE, shim your site with a single dom4 shim and fix the one thousand libraries you rely on after that. The absolutely worst you could do is ask each of those thousand libraries to fix a problem that only exists in browsers of which the people that make it don't even want you to keep using it (in this case, Microsoft _really_ does not want you on IE11 anymore, they want you to use Edge. Given that Edge actually supports the internet, that's a great position to hold for them, and I will help in this effort).
