### ISSUE TITLE
v6 blew uglifyjs

### ISSUE THREAD

**Issue by ignatiusreza** [Pomax/react-onclickoutside#184]
Updating to v6 breaks build which use ugilfyjs in the pipeline with:

> ERROR in app-32ad34666c9e041dfb35.js from UglifyJs
> Unexpected token: name (onClickOutside) [app-32ad34666c9e041dfb35.js:111558,33]

Which seems to be caused by [this line](https://github.com/Pomax/react-onclickoutside/blob/v6.0.0/index.js#L99) in the generated code (let is not valid in es5)

v5.11.1 doesn't have this issue..

**Comment by Pomax** [comment]
It's a major version update for a good reason: v6 is pure ES6, so you'll have to either tell uglify to run on modern JS, or run it after you've bundled everything with ES5 conversion.

**Comment by ignatiusreza** [comment]
closing this as duplicate of #185 , we're also having this issue in a webpack+babel setup
