### ISSUE TITLE
Provide a CHANGELOG

### ISSUE THREAD

**Issue by elado** [Pomax/react-onclickoutside#187]
To be able to track what's new and know about breaking changes.

(Thanks for this module!)

**Comment by Pomax** [comment]
technically you can trust a major version to properly break stuff, but if there's a tool that can help build changelogs without too much human interference, I'll be more than happy to add one.

**Comment by elado** [comment]
Like https://github.com/rvagg/changelog-maker ?
There are several tools for that, https://github.com/search?utf8=%E2%9C%93&q=%22CHANGELOG.md%22&type=

It's pretty common to add to libraries, would be greatly appreciated.

**Comment by Pomax** [comment]
changelog-maker is kind of a less useful way to do what https://github.com/pomax/react-onclickoutside/compare/v5.7.0...v6.0.0 already does, and that seems to be the norm rather than the exception: libraries like this keep the job of writing an actually useful changelog an arduous manual task. If you know of any specific ones that generate nicer changelogs instead of just writing out commit diff dumps, please let me know.

**Comment by GeKorm** [comment]
There's [lerna/lerna-changelog](https://github.com/lerna/lerna-changelog) which 'Uses github PR/Issue names categorized by labels with configurable headings'. It's used by [create-react-app/releases](https://github.com/facebookincubator/create-react-app/releases). Probably not much more useful than changelog-maker though. 

Even without automatic changelogs, a quick one-liner in the release page or CHANGELOG.md would be much appreciated. This package gets 150k downloads a week and there's no mention of the breaking changes in https://github.com/Pomax/react-onclickoutside/compare/v5.7.0...v6.0.0

**Comment by Pomax** [comment]
@GeKorm this project uses [semver](http://semver.org), so major version bumps are by definition breaking changes. That said, I'll have a look at lerna-changelog, thanks for the recommendation!

**Comment by elado** [comment]
semver is not a real solution for this. It still forces the user to re read all documentation to figure out the breaking change (which may be a function rename or a whole new API). A single liner description fire each version would be great. I wouldn't necessarily trust the generators because they probably rely on detailed PR description which might not always be the case. Anyway, thanks for the hard work.

**Comment by Andarist** [comment]
Ive added [release notes](https://github.com/Pomax/react-onclickoutside/releases) for v6+ and I plan to add new ones each time the library gets an update.
