### ISSUE TITLE
Unexpected token: name (onClickOutside) [./~/react-onclickoutside/index.js:92,0]

### ISSUE THREAD

**Issue by oarashi** [Pomax/react-onclickoutside#195]
I ran into a problem.
I'm using react-create-app and during build it causes error:
```SyntaxError : Unexpected token: name (onClickOutside) [./~/react-onclickoutside/index.js:92,0]```
Have you ever had similar issues or know how to handle it?

**Comment by DanilaGegele** [comment]
This HOC is a pure ES6 implementation as of v6.x - if you need ES5 code you can either use 5.x or below, or set up your build system so that it does ES5 conversion for you, at whatever is the most logical point in your build chain.

Use
yarn add react-onclickoutside@5.11.1

**Comment by Pomax** [comment]
v6.1.0 has been published and should address your problem. Please let me know if you're still running into this after udpating.

**Comment by amakhrov** [comment]
@Pomax Thanks, it has fixed the issue for me!
