### ISSUE TITLE
Wrapping with `onClickOutside` after wrapping with `connect()` causes error

### ISSUE THREAD

**Issue by tscizzle** [Pomax/react-onclickoutside#199]
There is an [Issue](https://github.com/Pomax/react-onclickoutside/issues/196) about nested HOC but hard to tell if same thing, so making new Issue.

This errors:

    MyComponent = connect()(MyComponent);
    MyComponent = onClickOutside(MyComponent);

saying this:

`Error: WrappedComponent lacks a handleClickOutside(event) function for processing outside click events.`

But this works:

    MyComponent = onClickOutside(MyComponent);
    MyComponent = connect()(MyComponent);

(`connect` is from Redux, by the way.)

Obviously I can just use the order that works, but figured it was worth letting people know on here! :D

**Comment by Pomax** [comment]
the HOC needs a `handleClickOutside` handler, either in the class you pass in, or passed in as an additional parameter in an options object, so this kind of "works as intended" in this case. The ordering matters since `connect()` hides the necessary function.

**Comment by tscizzle** [comment]
Oh interesting. I wasn't aware connect hid stuff. I thought it just returned the same component with all its stuff, with the addition of `dispatch` in the props and whatever else it adds.

Thanks!
