### ISSUE TITLE
TypeScript class support

### ISSUE THREAD

**Issue by DouglasLivingstone** [Pomax/react-onclickoutside#2]
I'm using TypeScript classes with React, which doesn't have support for mixins, so I've refactored this mixin for use in classes. Might be helpful if someone wants to use this with ES6 classes for example.

Here's a gist including a usage example. The mount/unmount calls need to be made explicit, but the rest is encapsulated in the class. https://gist.github.com/DouglasLivingstone/1c42108412bb12267a1c

**Comment by Pomax** [comment]
That's very interesting - I'm not too familiar with typescript classes, would you be able to explain why it can't work with the React concept of mixins? (are classes immutable/non-extensible?)

**Comment by DouglasLivingstone** [comment]
TypeScript classes are quite similar to ES6 ones, the main issue is that there isn't a standard way to do mixins: http://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#mixins

I'm using a hacky workaround to support mixins in some places with TypeScript, but I'm not planning to do that any more for the same reasons as in the React.js blog post above.

The main issue with mixins (even though it doesn't affect your onClickOutside mixin) is that a class like below won't type-check since there is no way for the compiler to know that the Bar mixin causes a .bar() method to get added to the class:

    class Foo {
        mixins = [Bar];
        render() {
            this.bar();
        }
    }

I've seen suggestions to extend base class support, something like this,

    class Foo extends mixins(Bar) {
        render() {
            this.bar();
        }
    }

but nothing really concrete.

**Comment by Pomax** [comment]
hm, I thought TypeScript had hints-through-comments for situations like those, to tell the component that the function you're about to call is not normally findable, but it's signature is "..."?

**Comment by DouglasLivingstone** [comment]
Interfaces can be used a bit like that, but I've never seen it done with comments in TypeScript.

**Comment by Pomax** [comment]
I might have to look at typescript more, but indeed https://typescript.codeplex.com/workitem/100 suggests that there is a way to make mixins work with normal compilation without a crazy amount of work by wrapping the mixin as an interface

**Comment by DouglasLivingstone** [comment]
More details on that method here: https://github.com/Microsoft/TypeScript/wiki/Mixins
