### ISSUE TITLE
Dependency cleanup

### ISSUE THREAD

**Issue by Andarist** [Pomax/react-onclickoutside#203]
So recently there were some changes regarding the build tooling etc, it was evolving process so i.e. some dependency were not cleaned up from `package.json` when they have stopped being used.

It needs a cleanup - I've filed initial PR with some basic tweaks https://github.com/Pomax/react-onclickoutside/pull/202

**Comment by Andarist** [comment]
@Pomax 
There are still rollup dependencies leftovers in the `package.json`. It should be decided if they should be removed or kept and being used for something.

It can still be valuable to leave it to:
- provide flat bundle (single file bundle - keeping internals hidden)
- build UMD version of the lib, so its easy to include on the webpage and experiment

**Comment by Pomax** [comment]
Let's not overload issues, though. The deps cleanup PR landed, if there is follow-up work, please file a new issue that says it's follow-up for this one. One issue, one PR: keeps things easy to track, easy to work on, and most importantly, easy for another contributor to help out with.
