### ISSUE TITLE
Rollup dependency cleanup

### ISSUE THREAD

**Issue by Andarist** [Pomax/react-onclickoutside#207]
Its a followup for #203

>There are still rollup dependencies leftovers in the `package.json`. It should be decided if they should be removed or kept and being used for something.
> It can still be valuable to leave it to:
> - provide flat bundle (single file bundle - keeping internals hidden)
> - build UMD version of the lib, so its easy to include on the webpage and experiment

**Comment by jochenberger** [comment]
See #230
