### ISSUE TITLE
Switch away from using PhantomJS

### ISSUE THREAD

**Issue by Andarist** [Pomax/react-onclickoutside#208]
**Reasons**:
- it has its bugs, i.e. https://github.com/Pomax/react-onclickoutside/pull/201#discussion_r125085507
- it's not really maintained anymore

**Solution** - use headless browser, i.e. Chrome or Firefox

**Comment by Pomax** [comment]
We can see if we can replace phantom with slimer, https://slimerjs.org/

**Comment by Andarist** [comment]
I suspect that integrating (even if tougher) with headless browser would give more benefits over time.

**Comment by Pomax** [comment]
agreed, but I talked to Brendan Dahl, who runs the effort to finish up the work on headless Firefox, and right now it's only supported on Linux and Windows, with OSX not quite there yet, so we can switch to slimer (which is already Gecko) as a stop gap measure. At least then we're not running into Phantom bugs.
