### ISSUE TITLE
Error with eslint no-unresolved since 6.2.0

### ISSUE THREAD

**Issue by tofumatt** [Pomax/react-onclickoutside#210]
See the error here: https://travis-ci.org/mozilla/addons-frontend/jobs/252183587#L1977

Since `6.2.0` I get the following error when running eslint against my repo (addons-frontend): `Unable to resolve path to module 'react-onclickoutside'  import/no-unresolved`

This happens for `6.3.x` as well. Not sure what caused it but it isn't happening elsewhere, wondering if there was a recent refactor/change of file structure that would've caused it.

**Comment by Pomax** [comment]
that's very odd, as 6.3 should have been a rollback to 6.1... let me try to re-rollback O_o

**Comment by Pomax** [comment]
@Andarist any idea?

**Comment by Pomax** [comment]
I've published 6.4, which should be a reversion to 6.1.1 - let me know if that's fixed things @tofumatt

**Comment by tofumatt** [comment]
[Passed all my tests](https://github.com/mozilla/addons-frontend/pull/2741). Thanks!

**Comment by Andarist** [comment]
@Pomax @tofumatt 
That is turbo strange o.O @tofumatt would u be able to provide a repository with reproduced issue? Would be helpful for debugging purposes.

**Comment by tofumatt** [comment]
Indeed, the repo is [addons-frontend](https://github.com/mozilla/addons-frontend/). Here are the relevant failing PRs:

* https://github.com/mozilla/addons-frontend/pull/2731 (`6.2.0`, possibly unrelated)
* https://github.com/mozilla/addons-frontend/pull/2732 (`6.3.0`)
* https://github.com/mozilla/addons-frontend/pull/2733 (`6.3.1`)

**Comment by Andarist** [comment]
Thanks, gonna set it up in a minute !

**Comment by Andarist** [comment]
Ok, I know what happened. `es` directory was not published on those versions, and the resolver (rightfully) tried to access it (as specified in `package.json`'s `module` entry).

@Pomax prepublish script should be added to ensure valid publications

**Comment by Pomax** [comment]
@Andarist whatever was the latest node 7.x with npm 3.x - I updated it since due to the Nodejs security advisory since, so maybe npm3 was too low and it needed 4 or 5?

**Comment by Andarist** [comment]
Hm, aint sure how to properly maintain `scripts` for various version of npm. there might not be any, but as only u have publishing rights and u have updated ur node and npm (from what I understand) - this shouldnt happen anymore.

Anyway - republishing what got reverted should be made I think.

**Comment by Pomax** [comment]
We should probably add an `engines` section to the package.json like `{ "engines" : { "npm" : ">=4" } }`

**Comment by Pomax** [comment]
@Andarist want to file a new PR with the changes on top of 6.4? I can then publish it with node 8/npm5 which should work.

**Comment by Andarist** [comment]
@Pomax , yeah, thought about adding `engines`, although they are just mere warnings (unless strict option is provided) and they also warn on installation of the package by the consumers, where we dont really want do that - we'd like to warn/error only during development of the package

**Comment by Andarist** [comment]
@Pomax wanted to send PR as requested, but im quite not sure how did u revert the changes and how the process went, dont want to mess up with history etc

I.e. this https://github.com/Pomax/react-onclickoutside/pull/201 was merged in according to github, but its not visible in the history, have u tampered with git's history by resetting it or smth? Same with this - https://github.com/Pomax/react-onclickoutside/pull/202

**Comment by Pomax** [comment]
I rolled back to the 6.1.1 release, and then forced that as master, then spun a new version directly from that. So the history between 6.1.1 and 6.4 has been removed from the master branch on github.

**Comment by Andarist** [comment]
I see you like living on the edge 😄 I'll send PRs with what got reseted in a minute
