### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by alesmenzelsocialbakers** [Pomax/react-onclickoutside#211]
The example should be updated to:
`const OnClickOutside = require('react-onclickoutside').default`

**Comment by Pomax** [comment]
not under ES6 rules.

> This HOC is a **pure ES6** implementation as of v6.x - if you need ES5 code you can either use 5.x or below, or set up your build system so that it does ES5 conversion for you, at whatever is the most logical point in your build chain.

**Comment by Andarist** [comment]
@Pomax actually when using `require` instead of `import` syntax `.default` is needed
