### ISSUE TITLE
Warning: CornerDialog(...): When calling super() in `CornerDialog`, make sure to pass up the same props that your component's constructor was passed.

### ISSUE THREAD

**Issue by RIP21** [Pomax/react-onclickoutside#212]
I got this error using this code:

```javascript
import styled from 'styled-components'
import React, { PureComponent } from 'react'
import PT from 'prop-types'
import { Box } from 'rebass'
import onClickOutside from 'react-onclickoutside'

class CornerDialog extends PureComponent {
  static propTypes = {
    show: PT.bool.isRequired,
    onClickOutside: PT.func.isRequired
  }

  props = {
    show: false,
    onClickOutside: () => {}
  }

  handleClickOutside = () => {
    this.props.onClickOutside()
  }

  render() {
    return this.props.show ? <Box {...this.props} /> : null
  }
}

export default styled(onClickOutside(CornerDialog))`
  position: absolute;
  right: 10px;
  top: 10px;
  background-color: gray;
  border-radius: 5px;
`
```
Working example:
[![Edit 9r2KYNBZB](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9r2KYNBZB)

Open console, clean it up, and press refresh, and two errors will appear. 
Will be very appreciated to know the root of the problem.

**Comment by Pomax** [comment]
I don't see any constructor in your code, which is kind of essential if you're extending from React's classes. A simplified example that works:

```js
import React, { PureComponent } from "react";
import onClickOutside from "react-onclickoutside";

class CornerDialog extends PureComponent {
  constructor(props) {
    super(props);
  }

  handleClickOutside() {
    console.log('x');
  }

  render() {
    return this.props.show ? <div>x</div> : null;
  }
}

export default onClickOutside(CornerDialog);

```

**Comment by RIP21** [comment]
@Pomax actually constructors are not mandatory. If I will have that, create-react-app linter will argue at me saying - useless constructor. So it works for all of my classes and should work for that too.
Hey @gaearon sorry for mentioning if not your case, but can you approve my words about constructor as well as the what can cause such warnings? 
Because I think it's a bug. 
Thanks.

**Comment by RIP21** [comment]
@Pomax actually constructor is not mandatory (create-react-app will argue at you for that one (useless constructor) it was my mistake having props field, instead of defaultProps.
