### ISSUE TITLE
onClickOutside is not a function

### ISSUE THREAD

**Issue by RomainGoncalves** [Pomax/react-onclickoutside#221]
Hi,

I'm having a little problem getting `react-onclickoutside` play nice with `storybook`.

I have a react component using `react-onclickoutside`. It works fine when I run my project, however when I try to load the component into Storybook, I get this error: `onClickOutside is not a function`

This only spot where I have this function call is in my component:

```javascript
var onClickOutside = require('react-onclickoutside');
[...]
exports.default = onClickOutside(ReactTelephoneInput);
```

I'm not sure if it's related but here's Storybook's Webpak config. It's pretty much the same as the project, just no entry/output declared. It works fine for all other components:
```javascript
const path = require('path');

module.exports = {
  module: {
    rules: [
      {
        test: /\.(png|woff|woff2|eot|ttf|svg)$/,
        use: ['url-loader?limit=100000']
      },
      {
        test: /\.scss$/,
        loaders: ["style-loader", "css-loader", "sass-loader"],
        include: path.resolve(__dirname, '../')
      }
    ]
  }
};
```

Thanks for any help.

**Comment by Pomax** [comment]
which version of this hoc are you using? Because if you're using the pure ES6 version, `require` syntax is not going to yield anything usable.

**Comment by Andarist** [comment]
If using `v6` and using `require` (instead of es6 `import`) you should require it like this:
```js
var onClickOutside = require('react-onclickoutside').default;
```

**Comment by RomainGoncalves** [comment]
hmm thanks guys for your answer. I'm using version `6.4.0`. Now you both might be right and I'll have to investigate a little more today. I'll get back to you once I know more.

Thanks again.

**Comment by RomainGoncalves** [comment]
Well I reverted to a previous commit in my project and it started working fine again. thanks for your time guys
