### ISSUE TITLE
add Andarist as co-maintainer

### ISSUE THREAD

**Issue by Pomax** [Pomax/react-onclickoutside#222]
I've had very little time to work on code in the recent past and this looks to stay the case for a while, so it would make a lot of sense to add @Andarist as maintainer with merge and publish rights.

Objections?

**Comment by Andarist** [comment]
None :trollface: Although I would like to have code 'guidelines' to which I should obey, as we've seen in the past that our opinions differ and I would like to follow your rules rather than just do as I please and like.

**Comment by Pomax** [comment]
A fair point - the main guideline I have is "keep devs responsible for their part of the job" so that the library doesn't start doing all kinds of things that someone's build system should be doing instead, within reason: if people start requesting functionality because modern build systems make it difficult to do what should be easy, then we can add those things in. 

The most important part of course is that tests keep passing and functionality does not break: I'm honestly okay with someone else determining the guidelines for a new version, since I'm simply not going to be able to look in too often anymore. Trying to hold onto the reins when I'm not even here seems... unproductive.

**Comment by Pomax** [comment]
you should have collaboration and npm publish rights now.

**Comment by Andarist** [comment]
Thanks for making me a collaborator on the project :) I certainly have some things in mind that I would like to change - some are currently in the PRs, some were declined before - and I would like to pursue them.

In the same time I certainly don't want to remove functionalities - maybe just provide other ways to achieve the same thing, for the benefit of the easier implementation.

One of such things would be to evaluate [this](https://github.com/Pomax/react-onclickoutside/blob/f6c3ef8b8ca2919190feca1435f2ef32ef68c9da/src/index.js#L60-L79) again. It always seemed to me that there is too much options here - but would have to think more about it and find good alternatives before changing it in any way.

**Comment by Pomax** [comment]
yeah, cc me when you're thinking about it "out loud" (in an issue) =D

**Comment by Andarist** [comment]
Sure thing :) For such big (possibly breaking for somebody) changes Im always opening issues for at least few weeks, so anybody can speak up.

Going to close this issue for now though, you can always contact me via email too :)
