### ISSUE TITLE
[typescript] error when calling HOC

### ISSUE THREAD

**Issue by jacek213** [Pomax/react-onclickoutside#225]
Used according with docs:

    import * as onClickOutside from "react-onclickoutside"

    class ContextDropdown extends React.Component<IProps, IState> {
    ...
    }

    const WithOnClickOutSide = onClickOutside(ContextDropdown)

yields error when using typescript 2.4.0 (latest ver of `@types/react-onclickoutside` installed):

`** Cannot invoke an expression whose type lacks a call signature. Type 'typeof "/.../node_modules/@types/react-onclickoutside/index"' has no compatible call signatures.**`

**Comment by Andarist** [comment]
I dont see any docs suggesting `import * as` syntax. Proper way to import the HOC is:
```js
import onClickOutside from "react-onclickoutside"
```
because we expose a default export.

**Comment by Andarist** [comment]
Closing because the author didn't respond for quite some time already.
