### ISSUE TITLE
Provide am UMD bundle

### ISSUE THREAD

**Issue by jochenberger** [Pomax/react-onclickoutside#229]
See #194, #202, #203, #207.

**Comment by Andarist** [comment]
Why do you think its needed? Would you use it? How? In what environment?

I'm curious, as I was always wondering about use cases for those nowadays.

**Comment by jochenberger** [comment]
I'm using it in an AMD environment. It's a Java application that uses RequireJS to load the JS modules.

**Comment by Andarist** [comment]
Do you copy the source code to your CDN servers or use something like unpkg?

Anyway I'm gonna provide it (was thinking about it anyway), probably later today (if I dont forget to do it 😄 )

**Comment by jochenberger** [comment]
No, I'm using [WebJars](http://www.webjars.org/).
I'm working on a PR.

**Comment by jochenberger** [comment]
Closing in favor of #230
