### ISSUE TITLE
Unable to find node on an unmounted component in React 16.0.0

### ISSUE THREAD

**Issue by jagi** [Pomax/react-onclickoutside#231]
I was trying to implement such a feature by myself but nothing worked as described on several websites. So I've encountered this package and it also does not work with React 16.0.0. I get the "Unable to find node on an unmounted component" error. Did anyone experience this problem?

It comes from usage of the `ReactDOM.findDOMNode` method. It's really strange because the component is mounted (I've checked that). Maybe it's a bug in React 16.0.0?

What is even more strange, when first I've used it it worked but after another a refresh it does not (without changing anything in the code). Maybe the problem comes from other tools that I'm using but I don't think so. However, I'm also using `styled-components` but I do wrapping properly.

```js
class Dropdown extends Component {
  constructor(props, context) {
    super(props, context);
    this.state = {
      isOpen: false
    };
  }

  handleClickOutside = (e) => {
    this.setState({
      isOpen: false
    });
  }

  /* ... */
}

const StyledDropdown = styled(onClickOutside(Dropdown))`
  position: relative;
`;

export default StyledDropdown;
```

Also, I think it's worth noting that I'm not using React for the entire application. The app is written using Meteor and Blaze and only some components are written in React. But does it make any difference in this case?

**Comment by Andarist** [comment]
Could u recreate issue on something like codesandbox so I can check it out quicker?

**Comment by jagi** [comment]
Sure, I will create reproduction

**Comment by jagi** [comment]
Hmm, it works properly in reproduction https://codesandbox.io/s/mm9qx1m829 but it's 99.9% the same code like the one I have in my app. The only difference it's that in the app React component is included in the Blaze template. So probably Blaze is causing some problems but finding out why will be tricky. Do you have any idea why it could cause the problem with the `ReactDOM.findDOMNode` function?

**Comment by Andarist** [comment]
I would start from setting up a breakpoint where `ReactDOM.findDOMNode` is called and inspecting the state of the browser at that moment.

**Comment by jagi** [comment]
I also created Meteor/Blaze reproduction and it's also working so the problem is in the project...
Thanks for the suggestion I will. I think we can close this issue as it's not package related

**Comment by jagi** [comment]
I found out what was the problem! I'm a little bit shocked that it didn't throw any warning or error. In this Meteor project, I was using two React versions 15 and 16. And from what I see the `ReactDOM. findDOMNode` checks what version is the "owner" and in my case it could tell so it was throwing an error. I think they should at least complain about two versions being used. Moreover, from what I remember there was a policy in Meteor that disallowed using two major versions of the same package and apparently it's not longer valid. I will post issues in both React and Meteor projects. I'm also leaving it here for posterity.

**Comment by Zaynex** [comment]
I meet the same issue.And I am using react16 based on `ceate-react-app`.

**Comment by harishv6665** [comment]
You saved my time. Thanks a lot, @lukejagodzinski.

**Comment by venugopalkathavate** [comment]
@lukejagodzinski Thank you for saving my time. I was thinking a long debugging session in my mind 🙂

**Comment by sheerun** [comment]
In my case it was connected with calling method in setTimout or throttle that tried to access old dom reference

**Comment by colourhand** [comment]
i have a problem like this,My solution is"   npm install  and npm start  " then  no  problem  like this

**Comment by mykeels** [comment]
In my case, I had to upgrade `react-test-renderer` to 16.6.0, and specify `{ disableLifecycleMethods: true }`:

```jsx
renderer.create(
    <Textfield component={options.componentData} />,
    { disableLifecycleMethods: true }
)
```

**Comment by thisismydesign** [comment]
For me, this was caused by updating `react-test-renderer` from `16.5.2` to `16.7.0`.

**Comment by nimeshkavinda** [comment]
> I found out what was the problem! I'm a little bit shocked that it didn't throw any warning or error. In this Meteor project, I was using two React versions 15 and 16. And from what I see the `ReactDOM. findDOMNode` checks what version is the "owner" and in my case it could tell so it was throwing an error. I think they should at least complain about two versions being used. Moreover, from what I remember there was a policy in Meteor that disallowed using two major versions of the same package and apparently it's not longer valid. I will post issues in both React and Meteor projects. I'm also leaving it here for posterity.

Dude you literally saved me! thank you so much

**Comment by shaianest** [comment]
hey watsapp https://codesandbox.io/s/cranky-mountain-ggwns?file=/src/App.js this  thank box is made and makes error from react-multilevel-select and from react-onclickoutside

**Comment by Pomax** [comment]
As a general practice when it comes to using github (for any project =), don't comment on a closed issue, but instead file a new issue and then link to the one (or multple) issue(s) that you thought might be related. That way any bugs or regressions (or sometimes even "works as intended and the fix will be somewhere else") can be tracked as new work.
