### ISSUE TITLE
IE11 Does not support classList on SVG

### ISSUE THREAD

**Issue by thebuilder** [Pomax/react-onclickoutside#232]
Been seeing a few errors in IE11 caused by [missing classList support on SVG elements](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/1173756/):

**dom-helpers.js**
```js
export function isNodeFound(current, componentNode, ignoreClass) {
  if (current === componentNode) {
    return true;
  }
  // SVG <use/> elements do not technically reside in the rendered DOM, so
  // they do not have classList directly, but they offer a link to their
  // corresponding element, which can have classList. This extra check is for
  // that case.
  // See: http://www.w3.org/TR/SVG11/struct.html#InterfaceSVGUseElement
  // Discussion: https://github.com/Pomax/react-onclickoutside/pull/17
  if (current.correspondingElement) {
    return current.correspondingElement.classList.contains(ignoreClass);
  }
  return current.classList.contains(ignoreClass);
}
```

I guess the quick fix is to just check for "classList" support, and return `false` if not supported.
Otherwise you'd need a IE11 specific class lookup method.

**Comment by Andarist** [comment]
https://github.com/Pomax/react-onclickoutside#ie-does-not-support-classlist-for-svg-elements

However, I will prepare a new version of the library soonish, which might not have this problem on default settings. No promises yet though.

In order to fix this in my application I'm using this dirty hack:
```js
if (!('classList' in SVGElement.prototype)) {
  Object.defineProperty(SVGElement.prototype, 'classList', {
    get() {
      return {
        contains: className => {
          return this.className.baseVal.split(' ').indexOf(className) !== -1
        },
      }
    },
  })
}

```

**Comment by thebuilder** [comment]
Ah, sorry - Missed that note. Just thinking it would be better to ignore the "ignoreClass" on IE11, rather than throwing an unhandled error. 

Thanks for the shim, i'll use that to fix it for now. 👌

**Comment by ButuzGOL** [comment]
seems like fix wasnt added ?

**Comment by Andarist** [comment]
You have to provide a shim for this, in the future version of the library "ignoreClass" wont be part of the core library, so you won't run into this in basic use case
