### ISSUE TITLE
Losing instanceRef

### ISSUE THREAD

**Issue by giuseppepaul-axiell** [Pomax/react-onclickoutside#233]
Hey! Hoping you could point me in the right direction, I'm using onclickoutside to help with some menus that appear for each row in a grid, I'm using React Virtualized (https://github.com/bvaughn/react-virtualized) to help with my Grids / Lists. 

React Virtualized does some clever voodoo where it shuffles lists to only render the items that are visible on screen and I think it's causing an issue with onclickoutside.

This is the error I'm getting:

```
Uncaught TypeError: Cannot read property 'getInstance' of null
    at onClickOutside.getInstance (http://localhost:6006/static/preview.bundle.js:54273:17)
    at onClickOutside._this.__outsideClickHandler (http://localhost:6006/static/preview.bundle.js:54194:30)
    at HTMLDocument.handlersMap.(anonymous function) (http://localhost:6006/static/preview.bundle.js:54235:17)
getInstance @ preview.bundle.js:54273
_this.__outsideClickHandler @ preview.bundle.js:54194
handlersMap.(anonymous function) @ preview.bundle.js:54235
```

The issue seems to be here:

```js
    /**
     * Access the WrappedComponent's instance.
     */
    onClickOutside.prototype.getInstance = function getInstance() {
      if (!WrappedComponent.prototype.isReactComponent) {
        return this;
      }
      var ref = this.instanceRef;
      return ref.getInstance ? ref.getInstance() : ref;
    };
```

Where this.instanceRef is returning null. The error doesn't seem to happen until the list paginates so I realise it's very unlikely to be a bug with onclickoutside but I'm just hoping you could maybe point me towards a fix or workaround for it.

Thanks!

**Comment by Andarist** [comment]
Hi! I can offer my debug in solving your issue - but you would have to reproduce it on something like codesandbox.io and provide a link for this ready-to-debug example.

**Comment by Pomax** [comment]
Also on a syntax note, single backticks are "inline" code, whereas triple backticks are for blocks of code that preserve newlines. I've edited your comment to use triple backticks, and you can see it looks much better this way =)

**Comment by Andarist** [comment]
@giuseppepaul-axiell any updates on the issue? Gonna close soon if you do not provide any more information.

**Comment by giuseppepaul-axiell** [comment]
Hey guys sorry for leaving this open, I'll go ahead and close it I just ended up swapping it out for something a little more manual to avoid the issue.

Thanks

**Comment by Andarist** [comment]
I would suspect this is issue with `ref`, not sure how it should be solved in enzyme though. I suspect u somehow need to mock node, like [here](https://github.com/andreypopp/react-textarea-autosize#how-to-test-it-with-jest-and-react-test-renderer).
