### ISSUE TITLE
create-react-app: fails to minify

### ISSUE THREAD

**Issue by ChristianTheMinery** [Pomax/react-onclickoutside#239]
When using facebookincubator/create-react-app to create an optimized web build for my application, I get the following error:

    Failed to minify the code from this file: 
       ./node_modules/react-onclickoutside/index.js:92

Any chance for this to be resolved by having the package be published pre-compiled?

**Comment by Andarist** [comment]
The package is published pre-compiled down to cjs and es modules formats (both being es5, except es modules ofc in the latter), there are also umd bundles available in the `./dist` directory (this also gets published.

I suspect this is some configuration problem, you would have to share repository with the issue reproduced if you want to get some help, otherwise we can't do much.

**Comment by ChristianTheMinery** [comment]
Hm, well one thing worth noting is that I'm not requiring this manually. I'm actually requiring the `react-datepicker` package (https://github.com/Hacker0x01/react-datepicker) which then depends on `onclickoutside` - so I'm not sure how much control I have over how its loaded.

**Comment by SpencerTorres** [comment]
@ChristianTheMinery 

From the `react-onclickoutside` Readme:
> This HOC is a pure ES6 implementation as of v6.x - if you need ES5 code you can either use 5.x or below, or set up your build system so that it does ES5 conversion for you, at whatever is the most logical point in your build chain.

I had a similar problem. My workaround (not recommended) was to install 5.x (`npm install react-onclickoutside@5.x`) and copy it into the `/node_modules/react-datepicker/node_modules` folder. This resulted in an awfully large build size, but I needed this update tonight, and it wasn't that big of a problem for my project.

This project is not at fault for the error, it seems to be based on the dependencies for `react-datepicker`

Perhaps a contributor over there could get it moved back to `5.x`?

**Comment by Andarist** [comment]
Our Readme is a little bit outdated. We have decided to bring back transpilation to es5 after many voices from the community. Need to update this part later.

`react-datepicker` has exact version of `react-onclickoutside` specified in the `package.json` - newer versions should work ok for you. I've sent PR with the change - https://github.com/Hacker0x01/react-datepicker/pull/1091
