### ISSUE TITLE
Const is not supported in Old safari version in Ipad.

### ISSUE THREAD

**Issue by sidzan** [Pomax/react-onclickoutside#242]
I got into some trouble with this package for old safari version in an ipad mini (safari /6XX). I am not sure if i need this package at all, but it has somehow been included and i believe some packagea are depenedet to it.

So the basic problem is the "const " is being used for declaration of some vars, or the file has not  used babel to transpile to es5.

I got around google searching for solution and found out some way to fix this is to change webpack config (which i am not sure what i need to do), or i create an issue here and some good folks here will fix it . 

Please let me know how to get around this issue, any suggestion comments are highly appreciated !

**Comment by Andarist** [comment]
Please check what package uses `react-onclickoutside` as dependency and please update their deps to the newest one. You shouldnt have any problem with latest version of `react-onclickoutside`.

**Comment by Pomax** [comment]
(closing as a matter of build system rather than specifically this library)
