### ISSUE TITLE
removeEventListener not being called in certain browsers

### ISSUE THREAD

**Issue by bdwain** [Pomax/react-onclickoutside#251]
The call to removeEventListener does not contain any options, and this means it will fail in certain browsers (see the Matching event listeners section of https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener). 

> It's worth noting that some browser releases have been inconsistent on this, and unless you have specific reasons otherwise, it's probably wise to use the same values used for the call to addEventListener() when calling removeEventListener().

This causes many errors once a component is unmounted (Cannot read property 'getInstance' of null).

I'll make a PR to add it.

The browser I have that runs into this issue is a Chrome 30 webview on a samsung tab 4 (i was surprised to see it passed the feature detection, but it does). But it's not all versions of chrome 30, (couldn't reproduce on browserstack). So sorry for being unable to provide a reproduction.

**Comment by bdwain** [comment]
added #252

**Comment by Andarist** [comment]
Need to investigate this, might take few days. Thanks for reporting the issue

**Comment by filmic** [comment]
Any update when that fix will be released?

We have the same issue on page using [TrackJs](https://trackjs.com/) which reimplements `addEventListener` / `removeEventListener` and requires the same options to be passed when calling `removeEventListener` to remove the listener.

You can see the issue on https://www.leovegas.com/en/sportsbook/#filter/football page - try to toggle between "Live & Upcoming" and "Outrights" tabs.

**Comment by Andarist** [comment]
I've asked for a small change under the PR - we should merge this soon.
