### ISSUE TITLE
Add support for Stateless Functional Components

### ISSUE THREAD

**Issue by SteveAtSentosa** [Pomax/react-onclickoutside#253]
There may be a way to use onclickoutside with Stateless Functional Components, but I could not figure out how.

If that is not supported, I think it would be extremely useful as many UI components are stateless functional

Thanks!

**Comment by SteveAtSentosa** [comment]
After further research, I was able to get onclickoutside working with stateless fxnl components.

See https://github.com/davishmcclurg/react-onclickoutside-issue/blob/master/src/App.js#L8

**Comment by anaspk** [comment]
I think this deserves to be explicitly mentioned in the Readme with example as all other cases are mentioned. Thanks @SteveAtSentosa for figuring this out and sharing your finding :-)
