### ISSUE TITLE
passing in disableOnClickOutside to an enhanced component blocks handleClickOutside from firing

### ISSUE THREAD

**Issue by jcursoli** [Pomax/react-onclickoutside#266]
when you create an enhanced component and pass in `disableOnClickOutside`, after you call `enableOnClickOutside()` it still does not trigger the `handleClickOutside` hook.

EXAMPLE: 

```
class ClickComponent extends React.Component {
  whenUserDoesSomething = () => {
    this.props.enableOnClickOutside();
  }
}
handleClickOutside = () => {
    // event never gets triggered
}
const EnhancedComponent = onClickOutside(ClickComponent);

class Container extends React.Component{
    render() {
        return <EnhancedComponent {...this.props} disableOnClickOutside={true} />;
    }
}
export default Container
```
This issues was reproducible on the latest release, but earlier versions it is not reproducible. I am using version 6.5.0 which does not have the issue.

**Comment by Razinsky** [comment]
I'm having the same issue here. I see the issue was logged a while ago, can you guys look into it please? Thanks!

**Comment by Pomax** [comment]
would you be willing to create a PR that adds a test case for this? If so, we (or you, if you like!) can write the code that makes sure to test that pass, rather than fail it.

**Comment by jcursoli** [comment]
@Pomax I made a PR (#296) to fix the issue. heres a codesandbox link with the new minified code for a demo.
[](https://codesandbox.io/s/k59o3v6yjr)

**Comment by jcursoli** [comment]
This has been fixed. https://github.com/Pomax/react-onclickoutside/releases/tag/v6.8.0
