### ISSUE TITLE
Typescript Error

### ISSUE THREAD

**Issue by blaadje** [Pomax/react-onclickoutside#272]
Hello,
I'v been trying to wrap a Popper with `react-onclickoutside`
and type script is giving me an error.
```bash
[tsl] ERROR in /home/alex/labs/movieRate/src/components/Popper/index.tsx(134,31)
      TS2345: Argument of type 'typeof BasePopper' is not assignable to parameter of type 'ComponentClass<iProps & InjectedOnClickOutProps & HandleClickOutside<any>> | StatelessComponent<i...'.
  Type 'typeof BasePopper' is not assignable to type 'ClickOutComponentClass<iProps & InjectedOnClickOutProps>'.
    Type 'BasePopper' is not assignable to type 'Component<iProps & InjectedOnClickOutProps, ComponentState, never> & HandleClickOutside<any>'.
      Type 'BasePopper' is not assignable to type 'Component<iProps & InjectedOnClickOutProps, ComponentState, never>'.
        Types of property 'props' are incompatible.
          Type 'Readonly<{ children?: ReactNode; }> & Readonly<iProps>' is not assignable to type 'Readonly<{ children?: ReactNode; }> & Readonly<iProps & InjectedOnClickOutProps>'.
            Type 'Readonly<{ children?: ReactNode; }> & Readonly<iProps>' is not assignable to type 'Readonly<iProps & InjectedOnClickOutProps>'.
              Property 'disableOnClickOutside' is missing in type 'Readonly<{ children?: ReactNode; }> & Readonly<iProps>'.
```

I dont really get it as it seems to te be an props incompatibility issue

Here is the code :
https://gist.github.com/blaadje/ded2509370449e21e09141f10e3bfd40

If you guys have any idea.

Thanks

**Comment by nickoneill** [comment]
I have this working in a react 16.2 typescript project, but I'm getting this same error in a new 16.3 project, not sure what's going on but I would love to use this in 16.3.

**Comment by blaadje** [comment]
Seems to be the same for me :S

**Comment by bogdan-zaharia-hs** [comment]
From what I see in the [type definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-onclickoutside/index.d.ts#L33), the props should actually have the type:

```ts
export type Props = YourProps & InjectedOnClickOutProps & HandleClickOutside<any>;
```

**Comment by blaadje** [comment]
Hi,

@bogdan-zaharia-hs trying this above which seems to be the good thing to do, still throws the same thing.
Pretty annoying as for now i have to modify `react-onclickoutisde` type definition file manually to make it works.
Any suggestion to make it works?

**Comment by Pomax** [comment]
Yeah: if you have to "manually modify the type definition", feel free to submit a PR, since you're already doing the work anyway =)

**Comment by ValentinnDimitroff** [comment]
@blaadje Until we have a solution could you share which part are you modifying?
