### ISSUE TITLE
Support React.Fragment

### ISSUE THREAD

**Issue by miraage** [Pomax/react-onclickoutside#274]
If a component has React.Fragment as root node, onClickOutside will trigger a false-positive and invoke handleClickOutside method.

[Demo](https://codesandbox.io/s/jv4nzok0w).

**Comment by rikjacobs1390** [comment]
Exact same "problem" here.

**Comment by Pomax** [comment]
We can probably except this element, but I'm wondering whether we should add this in as a configurable list of elements that are known disruptors for the cascade check. Are there any other known elements that might have this effect?

**Comment by rikjacobs1390** [comment]
I'm not quite sure what exactly you mean? The only issue i found was with a <React.Fragment /> . Easily solved by just using a <div />. But I think it's worth mentioning in the docs until fix/update!

**Comment by Pomax** [comment]
I mean in order to deal with this, React.Fragment, as a possible node root in addition to the `<html>` element, needs special case handling. Are there more roots that can cause this? (for instance, in a mixed React+other page, would a `document.createDocumentFragment` have the same effect)

**Comment by gaurav5430** [comment]
What was the final decision on this. I just stumbled on it while using React.Fragment, and it took me some time to figure out why onclick outside was triggering even though I was clicking inside the element. 

Is this fixed?
or added to documentation somewhere as a known exception ?
