### ISSUE TITLE
Uncaught ReferenceError: React is not defined @ index.js line 59

### ISSUE THREAD

**Issue by lfbayer** [Pomax/react-onclickoutside#28]
This was working in version 0.2.4 but using version 0.2.5 from npm, I get the following error from index.js at line 59...

```
Uncaught ReferenceError: React is not defined
```

It looks like you have made changes recently to how the dependencies are loaded. Do I need to do something in order to have React visible to onclickoutside?

**Comment by Pomax** [comment]
That depends on how are you trying to load it the library (node, AMD modules, pure browser). The relevant loader code is on lines https://github.com/Pomax/react-onclickoutside/blob/master/index.js#L15-L26

**Comment by lfbayer** [comment]
I'm using npm and webpack so I'm importing the package using "require".

**Comment by Pomax** [comment]
Hmm, that line 19 ought to work...  since it's a straight up require('react') call.

**Comment by lfbayer** [comment]
What changed between 0.2.4 and 0.2.5?

I'm not really familiar with how the require calls work under the covers. So to investigate this myself, I'm not sure where to start.

**Comment by Pomax** [comment]
The current version's 0.3.1, though?

**Comment by lfbayer** [comment]
Ah, that was it. My package.json said "^0.2.4" causing it to pull in 0.2.5. I changed it to "0.3.1" and it's working now.

I guess I don't know how the versioning from a package.json file works yet.

Thanks for your help!
