### ISSUE TITLE
Sometimes ref is null or undefined

### ISSUE THREAD

**Issue by heygrady** [Pomax/react-onclickoutside#281]
https://github.com/Pomax/react-onclickoutside/blob/cc1d179bd177615fab0204d0293b771a844068ba/src/index.js#L62

Probably related to https://github.com/Pomax/react-onclickoutside/issues/271

```
TypeError: null is not an object (evaluating 'ref.getInstance')
  File "webpack:///./node_modules/react-onclickoutside/es/index.js", line 136, in getInstance
          return ref.getInstance ? ref.getInstance() : ref;
  File "webpack:///./node_modules/react-onclickoutside/es/index.js", line 43, in __outsideClickHandler
            var instance = _this.getInstance();
  File "webpack:///./node_modules/react-onclickoutside/es/index.js", line 87, in [anonymous]
              _this.__outsideClickHandler(event);
```

We're getting a rollbar issue for this line of code (using version 6.6.2 but the relevant code looks identical to the latest version). We're indirectly including this library because it's a [dependency of react-datetime](https://github.com/YouCanBookMe/react-datetime/blob/master/package.json#L85) (used like [this](https://github.com/YouCanBookMe/react-datetime/blob/master/src/DaysView.js#L6-L9)).

Most of the errors are happening for us in old versions mobile Safari (9).

The precise cause of the issue here is hard to track down. However, it's clear that there are certain circumstances where `this.instanceRef` returns `null` or `undefined`. This is _probably_ due to funky edge cases where the wrapped component is unmounting or renders `null` or is otherwise not an expected value.

```js
getInstance() {
  if (!WrappedComponent.prototype.isReactComponent) {
    return this;
  }
  const ref = this.instanceRef;

  // In some rare circumstances the ref isn't defined or is null. This has been reported
  // to happen in Enzyme and has happened in the wild. It's possible that there are race
  // conditions that occur during mount/unmount that would cause the ref to be undefined.
  // Here we return undefined if we find ourselves in this undefined situation.
  if (!ref) {
    return undefined
  }
  return ref.getInstance ? ref.getInstance() : ref;
}
```

In `__outsideClickHandler`, `componentDidMount` and `componentDidUpdate` we rely on `getInstance` being a real instance. I suggest bailing in those functions if `instance` is not defined.

```js
// ...
const instance = this.getInstance();

// Bail when the instance isn't defined. This would only happen if there is an undefined
// instance ref. That would happen in weird edge cases. Regardless of why, if the ref
// isn't defined then bailing is probably the only rational choice.
if (!instance) {
  return
}
```

**Comment by heygrady** [comment]
Hmm, possibly fixed by https://github.com/Pomax/react-onclickoutside/issues/235

Going to try upgrading our react-onclickoutside dependency to latest and see if it resolves the rollbar issue for us.

**Comment by heygrady** [comment]
**Update:** so far so good. 0 occurrences since upgrading to latest version.

**Comment by Pomax** [comment]
sounds like you're no longer running into this.
