### ISSUE TITLE
Unable to get property 'contains' of undefined or null reference

### ISSUE THREAD

**Issue by leviking** [Pomax/react-onclickoutside#289]
https://github.com/Pomax/react-onclickoutside/blob/master/dist/react-onclickoutside.js#L54

Seems to be giving me issues where current has a `correspondingElement` but that element does not have a `classList`.

It seems to be hitting users in production intermittently but I can't seem to recreate the behavior. I can send you a PR, with a check that stops the error, but I was wondering if there's some reason why that would be happening that just isn't obvious to me.

**Comment by Pomax** [comment]
Every HTML element has a `.classList` property in modern browsers, so you're going to have be more detailed. Specifically, if this is about https://github.com/Pomax/react-onclickoutside#ie-does-not-support-classlist-for-svg-elements, please close this issue.

**Comment by leviking** [comment]
Thanks, I confirmed the user in question was using IE.
