### ISSUE TITLE
"InvalidCharacterError" exception on IE

### ISSUE THREAD

**Issue by Bbahri** [Pomax/react-onclickoutside#292]
We got an exception on svg elements that we fixed using the polyfill given in the documentation.

But, I still have an exception of type "InvalidCharacterError" on the following line in Internet Explorer 11:
return current.classList.contains(ignoreClass);
in the method "isNodeFound(...)".

I tried writting my own polyfill but it does'nt work as expected.

**Comment by Bbahri** [comment]
I fixed the probleme using these lines:
```
DOMTokenList.prototype.contains = function(classNames) {
  return classNames.toString().split(' ').indexOf(classNames) !== -1;
};
```

**Comment by Pomax** [comment]
Sounds like you fixed the problem, so I'll close this issue.
