### ISSUE TITLE
Callback fired twice?

### ISSUE THREAD

**Issue by kimmobrunfeldt** [Pomax/react-onclickoutside#3]
I didn't test this but it looks like the callback function might be called twice on mobile browsers which send touchstart and mousestart events. 

My source for mobile browser events was this question, so I'm not sure how accurate it is: http://stackoverflow.com/questions/14486804/understanding-touch-events You should probably somehow unify the pointer events.

**Comment by Pomax** [comment]
nice link, thanks. In a well implemented browser those events should be mututally exclusive, dependent on what caused the input to fire, but there are some that decide to violate that. I'm very busy this week with work deadlines and house guests (the worst combination for free time), but will try to see if I can make time for addressing this next week (unless someone's beaten me to it with a PR of course =)

**Comment by Pomax** [comment]
closing this issue with the release of v5.0.0 - if this still happens with the new version, please file a new issue.
