### ISSUE TITLE
WrappedComponent lacks a handleClickOutside(event) function for processing outside click events.

### ISSUE THREAD

**Issue by Robert-Fish** [Pomax/react-onclickoutside#303]
```
handleClickOutside = () => {
  console.log('hello world');
  };


export default connect(
  null,
  { toggleProject }
)(onClickOutside(ProjectDropdown));
```

I keep getting this error whenever i click on or near the component. "Uncaught Error: WrappedComponent lacks a handleClickOutside(event) function for processing outside click events."

**Comment by Pomax** [comment]
It looks like you tried to define a click handler in global scope, and that's never going to work.

As per the [installation](https://github.com/Pomax/react-onclickoutside#installation) section in the README.md: either decare the hander as a normal function that's part of your `ProjectDropdown` class, or make sure you have a click handler in the options object and use that when calling `onClickOutside(YourComponent, optionsObject)`.
