### ISSUE TITLE
handleClickOutside not bound when using functional Components with hooks

### ISSUE THREAD

**Issue by ZeroPie** [Pomax/react-onclickoutside#307]
Example:

```
const Menu = ({ userData }) => {
    const [isOpen, setIsOpen] = useState(false)
    const toggle = () => setIsOpen(!isOpen)
    const handleClickOutside = () => setIsOpen(false)
    

     return (
        <li className={isOpen ? "m-menu -active" : "m-menu "} onClick={toggle}>
...
        )
}
export default onClickOutside(Menu);
```

[![Edit vn66kq7mml](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vn66kq7mml)

Error:
```
react-onclickoutside.es.js:184 Uncaught Error: WrappedComponent lacks a handleClickOutside(event) function for processing outside click events.
    at onClickOutside._this.__outsideClickHandle```

**Comment by Pomax** [comment]
Hm, I don't see an immediate way to fix that, since the only two ways the HOC currently supports event handling is by either calling the handler that is part of the component's class, or by you explicitly saying what it as an options object, as second argument to `onClickOutside(Menu, {...})`.

**Comment by ZeroPie** [comment]
Hi, thanks for the answer:
Als the return Object is not extensible
```
TypeError: Cannot add property handleClickOutside, object is not extensible
```
I created a Codepen:

https://codesandbox.io/s/vn66kq7mml

**Comment by Pomax** [comment]
After a bit of puzzling, this will work:

```javascript
import React, { useState } from "react";
import "./Menu.css";
import onClickOutside from "react-onclickoutside";

const Menu = function() {
  const [isOpen, setIsOpen] = useState(false);
  const toggle = () => setIsOpen(!isOpen);

  // There are no instances, only the single Menu function
  Menu.handleClickOutside = () => setIsOpen(false);

  return (
    <li className={isOpen ? "m-menu -active" : "m-menu "} onClick={toggle}>
      <div> Open Menu </div>
      <ul className="m-menu__list">
        <li className="m-menu__item">
          <div className="m-menu__link">Log Out</div>
        </li>
      </ul>
    </li>
  );
};

var clickOutsideConfig = {
  handleClickOutside: function(instance) {
    return Menu.handleClickOutside;
  }
};

export default onClickOutside(Menu, clickOutsideConfig);
```

**Comment by ZeroPie** [comment]
Sweet, it works. Thanks a lot for your time!! 
Maybe it is a good idea to add a little snippet like this to the readme: ?

```
import React, { useState } from "react";
import onClickOutside from "react-onclickoutside";

const Menu = () => {
  const [isOpen, setIsOpen] = useState(false);
  const toggle = () => setIsOpen(!isOpen);
  Menu.handleClickOutside = () => setIsOpen(false);
  return (
      .../
  )
};

const clickOutsideConfig = {
  handleClickOutside: () => Menu.handleClickOutside
};

export default onClickOutside(Menu, clickOutsideConfig);
```
Thanks!

**Comment by koreyboone** [comment]
If for some reason you had multiple menus I don't believe this would work. I would only update the last one.

**Comment by Pomax** [comment]
Once you need multiple menus, generally you turn your functional component into a real class, because now you're dealing with a reusable component where it's important that there's some kind of `this` to tap into for event handling.

**Comment by Pomax** [comment]
@ZeroPie sounds like a good idea, would you be interested in stubbing out a PR for that?

**Comment by ZeroPie** [comment]
PR: https://github.com/Pomax/react-onclickoutside/pull/308
:) thanks!

**Comment by gpietro** [comment]
There is a way to access the state of the instance. I'm rewriting [react-numpad](https://github.com/gpietro/react-numpad) with hooks but I'm struggling to make work the onClickOutside.
https://gist.github.com/gpietro/67c9b2638421224671876df2dd59abfa#file-keypad-js-L133

**Comment by jmattheis** [comment]
Anything speaking against using a wrapper class?
```typescript
import * as React from "react";
import onClickOutside from "react-onclickoutside";

interface OnClickOutsideProps {
    onClickOutside: (event) => void;
}

export class XOutsideClickHandler extends React.Component<OnClickOutsideProps>{
    public handleClickOutside = (event) => this.props.onClickOutside(event);
    public render = () => this.props.children;
}

export const OutsideClickHandler: React.ComponentClass<OnClickOutsideProps> = onClickOutside(XOutsideClickHandler);
```
```typescript
export const Menu = () => {
    const [open, setOpen] = React.useState(false);
    return (
        <OutsideClickHandler onClickOutside={() => setOpen(false)}>
            <input type="button" onClick={() => setOpen(true)}/>
            {`menu is ${open}`}
        </OutsideClickHandler>
    );
};
```
If not, something like this should probably added to this repo.

**Comment by Pomax** [comment]
@gpietro @jmattheis can you both please file new issues, as they're different questions that warrant different discussions, neither of which should be taking place in a closed issue.

**Comment by Pomax** [comment]
(locked mostly to prevent more people from leaving comments on this closed issue)
