### ISSUE TITLE
The use of findDOMNode is deprecated in React Strict Mode

### ISSUE THREAD

**Issue by arqex** [Pomax/react-onclickoutside#315]
Hey! First thanks for this great library I've been using for so long.

It is used also inside of react-datetime and I got an issue from a user complaining about using `reactDom.findDOMNode`. Looks that it's going to be deprecated and we should move away from it.

Any alternative for removing it?

Cheers

**Comment by Pomax** [comment]
Does the warning tell you what should be used instead, by any chance?

**Comment by NamespaceValentine** [comment]
The docs suggest using refs:
https://reactjs.org/docs/strict-mode.html#warning-about-deprecated-finddomnode-usage

**Comment by Pomax** [comment]
given how this HOC works, refs are a problem until it's uplifted to use forwardRefs, so it might keep throwing warnings until we can get to updating it with those =(

(but if you want to take a stab at it, that'd be aweseme!)

**Comment by NamespaceValentine** [comment]
The main issue as I posted above, is that warnings now will become errors when this is used with upcoming react features.

**Comment by Pomax** [comment]
But React follows proper semver, and do not release minor versions that are backward incompatible. Those warnings will not turn into errors until React 17, at which point v6 of this library will become incompatible (just like how v5 is [incompatible with versions before v15](https://github.com/pomax/react-onclickoutside#which-version-do-i-need-for-which-version-of-react)). 

I'm not saying this shouldn't get fixed, but I _am_ saying that warnings are not errors, and this library will keep working with the main React component pattern just fine until that next major release comes out. So until then: if you want to take a stab at it, that's great, but I probably won't get to addressing this myself until I can find some time from my other engagements (or someone pays me to _make_ time and do this sooner).

**Comment by Pomax** [comment]
v6.9.0 published

**Comment by alpepe** [comment]
Hello, I see that the issue is closed, but I still notice it with me even though I up react-onclickoutsideit to version 6.10.0

"Warning: findDOMNode is deprecated in StrictMode...."

**Comment by Pomax** [comment]
was that a typo, or are you actually using something called `react-onclickoutsideit`? (because that would be a different project, then)

**Comment by alpepe** [comment]
Typo, sorry, what I'm using is "react-onclickoutside": "^6.10.0" exactly.

**Comment by Pomax** [comment]
Then you'll want to file a new issue, since this one got closed, with a minimum reproducible example so the problem's essentially reproducible with a copy paste. Thanks!

**Comment by brandondurham** [comment]
I see no newer issue. Was this resolved?

**Comment by Pomax** [comment]
I didn't see a new issue filed, so not yet
