### ISSUE TITLE
package strategy requiring 'react' will cause second copy of react to be loaded in some environments

### ISSUE THREAD

**Issue by florapdx** [Pomax/react-onclickoutside#32]
Line 18:  ```module.exports = factory(require('react'));``` will cause a second, possibly conflicting, version of React to be loaded in some project environments (I'll speak for mine only, where I'm requiring 'react/addons' in my source code). 

I have fixed this locally in the following ways:
a) changing line 18 in react-onlclickoutside's index.js to read ```'window.React || require('react')```,
b) adding browserify-shim to react-onclickoutside's package.json file and setting the shim config to:
 ```"browserify-shim": {
    "react": "global:React"
  }``` (note: this also requires dependency on browserify and setting the shim as a browserify transform).

I know that this is a common mixin pattern (and is required for using React's findDOMNode() accessor), so unsure if I'm missing a more obvious solution on my end?

**Comment by Pomax** [comment]
hmm, this might be better solved by making the module export be the factory itself, with an options object that contains the reference to react, defaulting to base react if omitted, so that people can control whether to use react or react/addons (or even a react shim, although I have no idea what that would look like)

**Comment by apreg** [comment]
I guess if you use webpack then you can solve this situation this way  
```
var path = require('path');
...
resolve: {
     alias: {
      'react': path.join(__dirname, 'node_modules', 'react')
    },
```

**Comment by Pomax** [comment]
I don't want to tie this to any one particular bundler, though.

**Comment by apreg** [comment]
I'm sure you don't, I just wanted to share this workaround till there is a better solution.

**Comment by Pomax** [comment]
:+1:

**Comment by Pomax** [comment]
v4 now uses react-dom, which has been split off from main react, so this conflict should no longer be an issue.
