### ISSUE TITLE
OCO applies only to last functional component

### ISSUE THREAD

**Issue by EdPutans** [Pomax/react-onclickoutside#325]
When multiple functional components are rendered by mapping, the onclickoutside only applies to the last component. This only occurs when defining the component as a stateless function, but works just fine when it's a class component.

**Comment by Pomax** [comment]
This feels like a consquence of how this HOC works - if you need more than one of these on a page, you're probably not better off with a functional component, and that thing should probably be a class. See https://github.com/Pomax/react-onclickoutside/issues/320 and https://github.com/Pomax/react-onclickoutside/issues/307

**Comment by jRichardeau** [comment]
Can you update the readme with this ? I lost a couple of hours with it.
