### ISSUE TITLE
On this github page right side, it says the latest release is 6.7 when it should be 6.9

### ISSUE THREAD

**Issue by fakdora** [Pomax/react-onclickoutside#345]

**Comment by Pomax** [comment]
The latest github-only release build was for 6.7.1, but the actual latest npm version/github tag is 6.9.0, which you'll also see noted in the README in the npm banner:

![image](https://user-images.githubusercontent.com/177243/97769848-82db9f00-1aeb-11eb-9d05-21138fb09105.png)
