### ISSUE TITLE
Using outsideClickIgnoreClass

### ISSUE THREAD

**Issue by majac91** [Pomax/react-onclickoutside#349]
From the <a href='https://github.com/Pomax/react-onclickoutside#marking-elements-as-skip-over-this-one-during-the-event-loop'>docs</a>, I can't exactly tell how ```outsideClickIgnoreClass``` is used. For example, what should be imported in this non-wrapped component and how do I ignore the .navLink: 

```
import React from 'react';

const Nav = () => {
  return (
    <ul>
      <li className={navLink}>Link to ignore</>
    </ul>
  );
}

export default Nav;
```

**Comment by Pomax** [comment]
nothing, because that code won't compile. `navLink` is nothing in the code you're showing, so your bundle compilation will error out. However, if you want any part of your DOM to get skipped, add the ignore class to their class list:

```
<li className="link secondary ignore-class-goes-here">This will get skipped over by onclickoutside</li>
```
