### ISSUE TITLE
Functional component docs issue

### ISSUE THREAD

**Issue by penx** [Pomax/react-onclickoutside#351]
The readme suggests to do the following:

https://github.com/Pomax/react-onclickoutside/blob/41ce5a6a6872fd1847ad6fd7f3d0b7412fd236b3/README.md#L83-L99

`Menu.handleClickOutside` is appending the handler to component definition rather than to the instance of the component, meaning this can introduce buggy side effects, e.g. if you were to have 2 instances of `Menu` then the handler would call twice for the second instance but not at all for the first instance.

This can be tested on the code sandbox linked in the docs https://codesandbox.io/s/vn66kq7mml

by: 
 - add a second instance of `<Menu />`
 - click on the first instance of Menu
 - click outside and note that the menu doesn't close

**Comment by Pomax** [comment]
There is no "component instance" when you're using a function, though. It's not a class/prototyped object. Instead, "the function gets run in several places". If you need to run your function multiple times in different places that all stay active, then yes, you can't "save" the handling as a function property.

**Comment by penx** [comment]
Is there any way to use `react-onclickoutside` on functional components that have multiple instances? If so, it would be good to have that approach in the docs.

I expect this would be a common use case, for example a custom select component. If there's not an alternative, I think it would be useful to add a caveat to the example in the docs.

**Comment by penx** [comment]
> There is no "component instance"

understood, it's just the best wording I could think of to describe the issue :)

**Comment by Pomax** [comment]
updated the docs, modern React basically doesn't need this HoC, it's trivial to implement with useRef and useEffect.

https://github.com/Pomax/react-onclickoutside/blob/master/README.md#functional-component-with-usestate-hook
