### ISSUE TITLE
Dropping support for react 16 (and 15)

### ISSUE THREAD

**Issue by ryanthemanuel** [Pomax/react-onclickoutside#357]
I noticed in 6.11.0 that support was dropped for react 16 and 15:

https://github.com/Pomax/react-onclickoutside/commit/da310a7dabec5ee2efb7a763d282a590f8925e77

With this change, people that were depending on ^6.0.0 of react-onclickoutside and react 16 will pull in 6.11.0 and react 16 and be broken. From my understanding of major versions, that type of change typically necessitates a major version bump of the package that makes the change (in this case react-onclickoutside).

**Comment by mgummelt** [comment]
Agreed.  This breaks several versions of `react-datepicker`, since it uses `react-onclickoutside@"`^6.8.0"` as a dependency.

**Comment by Pomax** [comment]
if so, that certainly wasn't intentional, I only bumped the rollup and webpack versions to the point where things bundled without crashing again, and karma testing passed.

**Comment by Pomax** [comment]
Looks like the version bumps also messed with the react versions, turning the nice `"^15.5.x || ^16.x || ^17.x"" into the fairly useless `"^17.x"` so let's _undo that immediately_.

**Comment by Pomax** [comment]
I've rolled back the dependencies to what they were before, and pushed out v6.11.2, let me know that fixes things because as far as I know, it should have.

**Comment by mjhenkes** [comment]
@Pomax 6.11.2 has corrected this issue for me. Thank you for the quick turn around!

**Comment by Pomax** [comment]
glad to hear it.
