### ISSUE TITLE
findDOMNode is deprecated in React StrictMode

### ISSUE THREAD

**Issue by Ruslan101** [Pomax/react-onclickoutside#369]
I used the react-onclickoutside (6.12.0) and I got this warning from React:

Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of AddExtModal which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at onClickOutside (http://mySiteName/static/js/vendors~main.chunk.js:77178:26)

**Comment by Slapbox** [comment]
This seems not very clean and easy to fix. Any solution is going to involve merging refs, if I'm not mistaken. Not impossible, but it's not gonna be pretty.

**Comment by Pomax** [comment]
Given the advances in JS, particularly the `contains` function, there might finally be a simple solution here, since we only need the HoC's own ref to determine whether clicks are inside or outside of the local DOM tree. I'll see if I have some time soon to pen a revision.

**Comment by JiDarwish** [comment]
Any update on this issue :) ?

**Comment by Pomax** [comment]
If you're using hooks: [yes](https://github.com/Pomax/react-onclickoutside#functional-component-with-usestate-hook). If you're using component classes, not yet.

**Comment by MrDevin12** [comment]
What amount of funding might you need to resolve this? @Pomax

**Comment by Pomax** [comment]
Uplifting dependencies and testing for v17, updating the code and writing additional test, updating the docs, and "not spending on other things that were on the top of the list" would probably put it at around $1000 (which I fully realise is well beyond the donation budget of an individual, but is a trivial one-time expense for a company that relies on open source)

**Comment by konossow** [comment]
It will be removed in React 19, see:
https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-reactdom-finddomnode

**Comment by Pomax** [comment]
Thankfully, no one needs this HoC anymore because React unfortunately went all-in on hooks, and the README.md gives you alternative code that'll do what you want without needing to install anything.
