### ISSUE TITLE
export IGNORE_CLASS from the module

### ISSUE THREAD

**Issue by goldensunliu** [Pomax/react-onclickoutside#37]
instead of remembering the special className: 'ignore-react-onclickoutside' for ignoring click outside. It would be a better source truth if it was exported from the module and/or have an option to config your own className

**Comment by Pomax** [comment]
can you show how you would see that used?

**Comment by goldensunliu** [comment]
maybe something like this for an option to specify your own className
``` javascript
clickOutsideMixin = require('react-onclickoutside').mixin('ignore-clickoutside');
component = React.createClass({
  mixins: [require('react-onclickoutside').]
  ...
})
```
and now the className is 'ignore-clickoutside'

for the case of simply exporting IGNORE_CLASS:
``` javascript
ignoreClickoutsideClassName =  require('react-onclickoutside').IGNORE_CLASS
```

**Comment by Pomax** [comment]
closing this issue, as the ignore class can be specified by devs who need that level of control.
