### ISSUE TITLE
stopPropagation breaks nested elements

### ISSUE THREAD

**Issue by mayorandrew** [Pomax/react-onclickoutside#39]
I have created JSFiddle to demonstrate the issue:
https://jsfiddle.net/69z2wepo/17780/

The problem is that when I nest two react elements with `OnClickOutside` mixin, the outer one stops receiving events. If I remove `stopPropagation` from the `__outsideClickHandler`, it works.

**Comment by Pomax** [comment]
can you explain an actual use case for a nested structure for which more than one element needs an outside click listener?

**Comment by mayorandrew** [comment]
I have a search page with filters panel. Panel may be opened by clicking on a "Open filters" button, or closed when clicked anywhere outside the panel. Panel has many selectboxes. Each one is a react component which shows its options on click and hides them on click outside. So the structure is similar to the JSFiddle demo where `Outer` element is like the panel and `Inner` is like the selectbox.

Also I've found more common use case which is not working with `stopPropagation`. It seems like when there are more than one element with `OnClickOutside` on the page, only the first one works.
https://jsfiddle.net/69z2wepo/17823/

**Comment by Pomax** [comment]
closing, filed https://github.com/Pomax/react-onclickoutside/issues/64 as generic solution issue.
