### ISSUE TITLE
React 14 functionality is introduced in react-onclickoutside 0.2.5

### ISSUE THREAD

**Issue by mhubenthal** [Pomax/react-onclickoutside#49]
React 0.13.0 functionality is introduced in react-onclickoutside 0.2.5 (findDOMNode function). Documentation should state that pre React 0.13.0 can be used up to react-onclickoutside 0.2.4, not 0.3.0

React 0.13.0 https://github.com/facebook/react/releases?after=v0.13.1

Thanks!

**Comment by Pomax** [comment]
fixed. That said, upgrading to any version that has React-DOM is a great idea =)

**Comment by mhubenthal** [comment]
@Pomax thanks! Agree on using up to date React, just stuck with supporting a slower moving project right now!
