### ISSUE TITLE
4.1.1 dist cannot be used as asset

### ISSUE THREAD

**Issue by hatched** [Pomax/react-onclickoutside#50]
We aren't able to use 4.1.1 because we have `index.js` being included directly in an application as an asset. It fails with a syntax error because `global` is not defined. I'd issue a PR but I'm not entirely sure when or why `global` would be defined. 

Issue was introduced here: https://github.com/Pomax/react-onclickoutside/pull/48

Using React 0.14.x

Workaround: downgrade to 4.1.0

**Comment by Pomax** [comment]
Can you explain why? This sounds like a side effect of improperly importing the library.

**Comment by Pomax** [comment]
marking as duplicate of #51
