### ISSUE TITLE
HOC not working

### ISSUE THREAD

**Issue by bzums** [Pomax/react-onclickoutside#52]
Hi,
I am trying to use the onclickoutside functionality via the HOC. Here is my (shortened) code:

```
import React, { Component, PropTypes } from 'react';
import listensToClickOutside from 'react-onclickoutside/decorator';

class FilterInput extends Component {

  ...

  handleClickOutside (event) {
    console.log('outside');
  }

  ...

}

export default listensToClickOutside(FilterInput);

```

But the `handleClickOutside` function is never called. Am I missing something?

Best,
    Basti

**Comment by Pomax** [comment]
no, 4.2 was missing a criticial bit of code that made the "window" binding disappear. 4.3 should have this fixed.

**Comment by bzums** [comment]
Mm that is still not working for me, do you have an working example maybe?

**Comment by Pomax** [comment]
no, but there was a typo still in 4.2, 4.4 should work fine
