### ISSUE TITLE
Bundling seems to be broken with babel 6 due to a typo in module.exports

### ISSUE THREAD

**Issue by EdwardDrapkin** [Pomax/react-onclickoutside#54]
This (in index.js): 

    // Node. Note that this does not work with strict
    // CommonJS, but only CommonJS-like environments
    // that support module.exports
    module.exports = factory(require(root, 'react-dom'));

Should probably be this: 

    // Node. Note that this does not work with strict
    // CommonJS, but only CommonJS-like environments
    // that support module.exports
    module.exports = factory(root, require('react-dom'));

**Comment by Pomax** [comment]
fixed by the linked PR
