### ISSUE TITLE
Could I get 'this' in the handleClickOutside function?

### ISSUE THREAD

**Issue by hank7444** [Pomax/react-onclickoutside#59]
I tried but I got undefined, have anyway to get it?
I would like to setState after triggered the event.

**Comment by Pomax** [comment]
can you show the class code you're using? `this` should just work

**Comment by richarddewit** [comment]
Are you using an ES6 `class`? Then you should define 
``` js
this.handleClickOutside = this.handleClickOutside.bind(this);
```
in your class' constructor. Otherwise, `this` refers to the function itself.

**Comment by hank7444** [comment]
thx all! I'll try it!

**Comment by hank7444** [comment]
@Pomax, @richarddewit, I fotget bind this, thx!!
