### ISSUE TITLE
handleClickOutside called because child element no longer in DOM

### ISSUE THREAD

**Issue by scoarescoare** [Pomax/react-onclickoutside#63]
I have an issue where elements inside the `OnClickOutside` component are removed before the `isSourceFound` function is called.

Specifically, I'm using https://github.com/JedWatson/react-select (a dropdown component).

```javascript
<MyOnClickOutsideContainer>
  <ReactSelect />
</MyOnClickOutsideContainer>
```
Once a value is selected in the `<ReactSelect/>` component, then `handleClickOutside` is invoked. This is because `isSourceFound` looks to see if `event.target` is contained within `MyOnClickOutsideContainer`, however `event.target` **isn't** contained because it's already been removed from the DOM.

For the time being, I've done:
```javascript
  componentWillMount(){
    // this was happening because the react-select component was removing its contents before this event would fire.
    // by the time the event fired, the element was already removed from the DOM.
    this._oldHandleClickOutside = this.handleClickOutside;
    this.handleClickOutside     = (evt)=> {
      //http://stackoverflow.com/a/16820058/173957
      if (document.body.contains(evt.target)) {
        return this._oldHandleClickOutside(evt);
      }
    };
  },
```

**Comment by Pomax** [comment]
I'm not entirely sure I understand the particulars here, is the problem that using the ReactSelect element triggers an "outside" event, despite the original action having taken place "inside"? Or is that "outside" *should* trigger, but does so with wrong data?

**Comment by scoarescoare** [comment]
> is the problem that using the ReactSelect element triggers an "outside" event, despite the original action having taken place "inside"?

Yes. I'm not sure the best way to describe the issue, but essentially ReactSelect is rendered within an `OnClickOutsideElement`. When I select a value in ReactSelect, it triggers the click event that will eventually invoke `IsSourceFound` **but before** that happens, ReactSelect removes the `evt.target` from the DOM. Because the node has been removed by the time `IsSourceFound` is called, `IsSourceFound` will evaluate to false in the [while loop](https://github.com/Pomax/react-onclickoutside/blob/master/index.js#L71).

**Comment by Pomax** [comment]
if you open the index.js in the node_modules/react-onclickoutside dir, and change https://github.com/Pomax/react-onclickoutside/blob/master/index.js#L111-112 to read this:
```
        document.addEventListener("mousedown", fn, true);
        document.addEventListener("touchstart", fn, true);
```
does ReactSelect still "win", or do things work? (this feels like a race condition where reactselect gets the act first on the same event, to which the half-solution is to make the onoutside check kick in "first". Which it can't, it can only request it be given priority (that `true` in the code update), but if ReactSelect also does that, then we're out of luck.

**Comment by scoarescoare** [comment]
Yeah, I agree about the race condition comment. I don't understand how react-select can handle the same click event *and* perform its `render` all before `IsSourceFound` gets invoked, but I guess that means I don't know enough about react internals.

So adding `useCapture` to true sort of works. It prevents `onClickOutside` from being invoked, however, it appears to prevent child elements from being captured? I say this because the react-select event handlers are no longer being called.

FWIW, the snippet I posted above `if (document.body.contains(evt.target))` seems to get the job done for me, but it may not be suitable for everyone else.

**Comment by Pomax** [comment]
hm, that might be because of https://github.com/Pomax/react-onclickoutside/blob/master/index.js#L63

**Comment by frank-weindel** [comment]
Had this exact same problem with react-onclickoutside and react-select. The workaround works great for me. 

I would think though that NOT triggering handleClickOutside when the target element is part of a detached DOM node would be a sufficient universal fix. I don't think that kind of situation is likely to happen in any other scenario so doing it that way should solve more problems than it could potentially cause.

**Comment by Pomax** [comment]
sure - if you know of a way for an element to tell whether it's in a detached fragment vs. part of the actual dom, I'm all ears. (well, eyes, but eh; details)

**Comment by frank-weindel** [comment]
Shouldn't it be as easy as looking for a node that has no parent and is also not the document? The while loop that looks for the source node could just add this check in there. I'll write this PR if you think this should be sufficient.

**Comment by Pomax** [comment]
True, although you'll need to run up the entire chain all the way to the document, rather than stopping at `html` or `body`; elements can live in fully qualified documentFragments that only signal it's detached by virtue of that document not being equal to window.document

**Comment by chrisirhc** [comment]
I've created a very simple PR based off this discussion. @frank-weindel hope you don't mind.

**Comment by Pomax** [comment]
looks good to me, it shouldn't interfere with previous behaviour, but if it does let's wait for someone to report it being broken.

**Comment by Pomax** [comment]
v4.6.0 pushed to npm

**Comment by frank-weindel** [comment]
@chrisirhc Thanks for knocking it out!
