### ISSUE TITLE
disableOnClickOutside ES6/2015 class support

### ISSUE THREAD

**Issue by klassicd** [Pomax/react-onclickoutside#65]
When using ES6 classes setting the property `<Component disableOnClickOutside={true} />`

Will overwrite the ability to use `this.props.disableOnClickOutside();` within the component class.  A simple solution I'm using now is to rename the property. 

```if (!this.props.disableOnClickOutside) {
        this.enableOnClickOutside();
}``` 

to 

```if (!this.props.disabled) {
        this.enableOnClickOutside();
}```

**Comment by Pomax** [comment]
closing due to the release of v5.0.0 - the functionality is now a pure HOC solution with `props` pass-through, and README.md documentation that clarifies how to use its new form.
