### ISSUE TITLE
Pass which document events to bind to

### ISSUE THREAD

**Issue by thomasjshafer** [Pomax/react-onclickoutside#67]
As created here: https://github.com/Pomax/react-onclickoutside/blob/master/index.js#L111 . 

In my example I have a dialog box that is opened via an onClick of a button. Then I use react-onclickoutside to close the dialog. However, if the user clicks on the button to close the dialog the document 'mousedown' event fires, the dialog wrapper state is set to closed, then the `onClick` event on the button fires and the dialog is set back to open. Essentially making the dialog flash closed then back open. I can make it work by having the button respond to an `onMouseDown` which will properly respect the `stopPropagation()`. 

It would be helpful to be able to pass in which document listeners to bind to.

I'm using HOC btw, so it's similar to the same design issue as https://github.com/Pomax/react-onclickoutside/pull/61.

Thanks!

**Comment by Pomax** [comment]
#61 got closed due to the code having been rewritten as HOC-only v5.0.0, but updating the events used should still be possible. I probably won't get to that today, so if you want to help get that added fast, I will be happy to review any PRs that get filed to (re)introduce this.

**Comment by sparksm** [comment]
is this addressed with `v5.2.0`?

https://github.com/Pomax/react-onclickoutside#regulate-which-events-to-listen-for

**Comment by Pomax** [comment]
yes, thanks for reminding me.
