### ISSUE TITLE
Need tests and CI

### ISSUE THREAD

**Issue by moodysalem** [Pomax/react-onclickoutside#74]
The error in the most recent release could probably have been avoided

**Comment by Pomax** [comment]
agreed, but not something I will have time for in the near future - if you know someone willing to add those, or want to take a stab at it yourself, I'll be more than happy to merge that work in.

**Comment by rafeememon** [comment]
I'll take a stab at this.  Will report back

**Comment by Pomax** [comment]
the test framework's been merged in, and while there is a low number of tests (two, right now), adding more tests based on bugs found will now be much easier (as in, possible, rather than not even possible)
