### ISSUE TITLE
Uncaught TypeError - getBoundingClientRect

### ISSUE THREAD

**Issue by BinaryWasteland** [Pomax/react-onclickoutside#83]
I keep getting the following error on scrolling my React page:

Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null

in the Helpers file line 116

any thoughts?

**Comment by Pomax** [comment]
hm, `getBoundingClientRect` is not used in this library, nor is there a "helpers file" (there's only an index.js and a decorator.js) so I suspect this is a problem with code outside of this library.
