### ISSUE TITLE
onClickOutside is not a function

### ISSUE THREAD

**Issue by tscok** [Pomax/react-onclickoutside#86]
Whatever I try I get this error `onClickOutside is not a function`.

I even copied the example code. Only modification I did was to add `render()` to MyComponent and `export default Container` to be able to import the component in other places.

What am I doing wrong??

```
var React = require('react');
var onClickOutside = require('react-onclickoutside');

var MyComponent = onClickOutside(React.createClass({
  handleClickOutside: function(evt) {
    // ...
  },
  render() {
    return this.props.children;
  }
}));

var Container = React.createClass({
  render: function(evt) {
    return <MyComponent disableOnClickOutside={true} />
  }
});

export default Container;
```

EDIT:
My setup is
- react 0.14.7
- react-onclickoutside 4.9.0

**Comment by tscok** [comment]
Nevermind. I uninstalled the package and re-installed it. Works like a charm now! 😄

**Comment by Pomax** [comment]
=P

**Comment by gabrielhpugliese** [comment]
Reinstalling the package did not solve for me. It is an object on react-onclickoutside@5.3.1
![image](https://cloud.githubusercontent.com/assets/1252818/16310745/26c2d5cc-3944-11e6-9ad6-8ccbc9f8f450.png)

The right way to use on ES2015 is wrapping your component like this:
```
<onClickOutside>
  <MyComponent>
</onClickOutside>
```

**Comment by VisorsJimmyTruong** [comment]
I had the same problem! I fixed it by re-installing as well but had to up the version from 4.9.0 to 5.11.1. 

Works : ) yay

My setup is 
react: 15.3.0,
react-onclickoutside 5.11.1

**Comment by Pomax** [comment]
@VisorsJimmyTruong the current version is 6.x, though.

**Comment by VisorsJimmyTruong** [comment]
@Pomax  for some reason I couldn't get 6.x to work. I even installed and re-installed 6.x 

0.0 perhaps cause of my setup's react version?

**Comment by Pomax** [comment]
could be. 6 is for React 15.5 and up (which I can recommend moving to as soon as possible so that React 16 doesn't catch out your codebase when it's released about 6 months from now)
