### ISSUE TITLE
React/ES6 handleClickOutside not bound

### ISSUE THREAD

**Issue by calvinnwq** [Pomax/react-onclickoutside#87]
Before v5.0.0, when you used the HOC, handleClickOutside was bound. Now it seems I have to bind it in my constructor, otherwise I cannot access `this.props` in my event handler.

```
constructor() {
  super();
  this.handleClickOutside = this.handleClickOutside.bind(this);
}
```

Should this be the case?

**Comment by Pomax** [comment]
Hm, it shouldn't - if you change https://github.com/Pomax/react-onclickoutside/blob/master/index.js#L108 to read `instance.handleClickOutside.bind(instance)` does the problem go away? If so, that should be a fairly quick fix (and can be spun off into a release relatively easily)

**Comment by calvinnwq** [comment]
Updating line 108 to `instance.handleClickOutside.bind(instance)` fixes it.
