### ISSUE TITLE
React 15.0.1 - warning about binding

### ISSUE THREAD

**Issue by george-cz** [Pomax/react-onclickoutside#89]
Hi,
I've recently updated React in my app to version 15.0.1 and since then, this warning has been poping up in console: 

`app.js:5245 Warning: bind(): You are binding a component method to the component. React does this for you automatically in a high-performance way, so you can safely remove this call. See Dropdown`

When I remove react-onclickoutside implementation in my Dropdown component, the warning disappears, obviously. Are you planning to address this issue?

Thanks

**Comment by Pomax** [comment]
React warns about this even for functions that React *does not automatically do this for*, so the problem here is React saying the wrong thing. The bind is extremely necessary, but if there's a way to suppress React's lie about autobinding, I'll be happy to work that in.

**Comment by george-cz** [comment]
Thanks for your reply,

have you considered moving the responsibility of binding the function to the component actually using it? I mean React.createClass auto binds functions, writing ES6 classes you can do something like 
```
handleClickOutside = (ev) => {
 alert("hi");
}
```
which is also auto-bound, if I'm correct. Then accessing `instance.handleClickOutside` in your library should always be function with the right context.

**Comment by Pomax** [comment]
That only works when ES6 syntax is supported, which will not be an option until Node 4.x goes out of LTS in October in favour of 6.0 (which has ES6 enabled by default with 93% spec coverage)

**Comment by george-cz** [comment]
Hi, for everyone having the same issue, i overcame this by setting `autobind: false` to my component: `React.createClass({autobind: false})`. Then manually binding any of my callback methods to `this`.
