### ISSUE TITLE
Ignore clicks inside certain elements

### ISSUE THREAD

**Issue by arunthampi** [Pomax/react-onclickoutside#9]
I have a requirement where I need the mixin to callback if its click outside a component but with a few exceptions. The method I used was to add the class `ignore-react-onclickoutside` to whichever elements that I want the mixin to ignore and change this line

https://github.com/Pomax/react-onclickoutside/blob/b9842bf81f75ed7fcebab38f503eb52cea9b9927/index.js#L51

to 

```javascript
found = (source === localNode || source.className.match(/ignore-react-onclickoutside/));
```

If you think this is a valid feature request (and solution), I can send a pull request (with the appropriate documentation changes as well).

**Comment by Pomax** [comment]
If you're up for writing a PR for it, I'll be happy to look it over - it sounds like a good additional control to have!

**Comment by arunthampi** [comment]
Done

**Comment by Pomax** [comment]
thanks! left two comments on how we can do this without needing regexp matching, other than that this looks extremely sensible to me!

**Comment by Pomax** [comment]
v0.2.3 published to npm

**Comment by arunthampi** [comment]
sweet, thanks for the super quick turnaround!
