### ISSUE TITLE
JSX syntax usage

### ISSUE THREAD

**Issue by savovs** [Pomax/react-onclickoutside#90]
Hi there, I'm using [this way](https://github.com/airbnb/javascript/tree/master/react) of writing React and I'm trying to access the click outside functionality. Could you please suggest how to do it in this case:

```javascript
import React from 'react';
import OnClickOutside from 'react-onclickoutside';

export default class Menu extends React.Component {

	constructor(props){
		super(props);
	}


	render() {

		return (
			<OnClickOutside>
				<ul>
					<li>Test 1</li>	
					<li>Test 2</li>	
					<li>Test 3</li>	
				</ul>
			</OnClickOutside>
		);
	}


    handleClickOutside(event) {
    	console.log('Clicked outside.');
    }
}

```

**Comment by Pomax** [comment]
What does it say when you use this syntax?

**Comment by savovs** [comment]
This solved my issue:
http://stackoverflow.com/questions/36961465/wrapping-a-high-order-componenthoc-around-a-react-component-in-jsx

**Comment by Pomax** [comment]
ah, good to know. Thanks for filing and solving!
