### ISSUE TITLE
5.1.0 nextProps enabling and disabling conditions identical

### ISSUE THREAD

**Issue by conoremclaughlin** [Pomax/react-onclickoutside#92]
Hi,

Love the idea and the work you've put into this library . We're rewriting our site in React and were using it to create some lightweight dropdowns. 5.1.0 seems much faster from 4.x but that's likely due to our limited knowledge of react.  Integrating it though we noticed the componentWillReceiveProps if conditions are identical so disableOnClickOutside wasn't being called properly.

See: https://github.com/Pomax/react-onclickoutside/blob/master/index.js#L131

We flipped it and now it's working magnificently.  Don't have time to open a proper pull request until next week cause of our tight deadline, but hope this helps and thanks for helping the community through a mostly thankless job.  If I've got this wrong, please don't hesitate to let us know. Our fix:
 
```
        componentWillReceiveProps: function componentWillReceiveProps(nextProps) {
          if (this.props.disableOnClickOutside && !nextProps.disableOnClickOutside) {
            this.enableOnClickOutside();
          } else if (!this.props.disableOnClickOutside && nextProps.disableOnClickOutside) {
            this.disableOnClickOutside();
          }
        },
```

**Comment by Pomax** [comment]
Allow me to blow your mind: click "edit this file" on https://github.com/Pomax/react-onclickoutside/blob/master/index.js, and just drop your code in, in the right place, then make a pull request without ever having to clone, use a text editor, or any of the other inconveniences if you just have a simple fix that you want to send up and forget about =)

(Github added some really nice things recently)

**Comment by conoremclaughlin** [comment]
Mind legitimately blown. We have some great use cases for this where it'll eliminate a lot of hassle.  Opened a pull request for ya.  Thanks for the tip =)

**Comment by Pomax** [comment]
it made github so much nicer for getting contributions for things that are tiny, but would otherwise still take more time "than it's worth". Honestly, github didn't yell about that feature loud enough when they added it =)

I've merged the code and will spin a new release.

**Comment by Pomax** [comment]
v5.1.1 published to npm
