### ISSUE TITLE
Internet explorer 11 specific undefined/null reference

### ISSUE THREAD

**Issue by Vibhanshu3** [Pomax/react-onclickoutside#95]
I am using leaflet in conjunction with react-onclickoutside, and currently the following code breaks in internet explorer 11(and only internet explorer among the popular browsers). /index.js
```
  var isSourceFound = function(source, localNode) {
    if (source === localNode) {
      return true;
    }
    // SVG <use/> elements do not technically reside in the rendered DOM, so
    // they do not have classList directly, but they offer a link to their
    // corresponding element, which can have classList. This extra check is for
    // that case.
    // See: http://www.w3.org/TR/SVG11/struct.html#InterfaceSVGUseElement
    // Discussion: https://github.com/Pomax/react-onclickoutside/pull/17
    if (source.correspondingElement) {
      return source.correspondingElement.classList.contains(IGNORE_CLASS);
    }

    return source.classList.contains(IGNORE_CLASS); //This line throws source.classList is undefined error
  };
```

I realize you guys have updated since I installed the module, but the error would still remain. There should be a check that ensures source.classList is defined before looking for the property contains.
A simple fix is to replace the last line with
`return source.classList && source.classList.contains(IGNORE_CLASS); `

Cheers!

**Comment by rafeememon** [comment]
Please see the [other issues](https://github.com/Pomax/react-onclickoutside/issues?utf8=%E2%9C%93&q=classlist+ie) and [readme](https://github.com/Pomax/react-onclickoutside/blob/master/README.md#ie-does-not-support-classlist-for-svg-elements) regarding this issue; tldr is that you should use a `classList` polyfill to support old (unsupported by Microsoft) versions of IE.

**Comment by Vibhanshu3** [comment]
I did read the issues and the readme. I am running the latest Internet explorer version (11...), so that is not the root cause.

**Comment by Pomax** [comment]
it is, though - IE for some bizar reason decided to support `classList` on everything *except* SVG elements, so you still need a classList shim, even on IE11.

**Comment by Vibhanshu3** [comment]
You're right. Thanks :)
