### ISSUE TITLE
Support for stateless components

### ISSUE THREAD

**Issue by tricoder42** [Pomax/react-onclickoutside#98]
I tried to use this lib with [recompose](https://github.com/acdlite/recompose/blob/master/docs/API.md#setproptypes):

```js
const controller = compose(
    withHandlers({
        handleClickOutside: (props) => (event) => null // do something
    }),
    onClickOutside
);

const component = controller((props) => <div>...</div>);
```

Unfortunately, onClickOutside HOC expects component with `handleClickOutside` method defined in component itself, so it doesn't work with stateless components.

Right now I'm using simple component using existing API which I use a root component in my stateless one:

```js
@onClickOutside
class OutsideClickHandler extends Component {
  handleClickOutside() {
    this.props.handleClickOutside();
  }

  render() {
    return this.props.children;
  }
}
```

Question is: Is it worth to include such a component in this library? Is there a better way how to support stateless components or take handler function from props?

**Comment by Pomax** [comment]
hmm, we could amend the HOC to call either `component.handleClickOutside` or if that is not avaiable, `props.handleClickOutside`.

**Comment by marcusnielsen** [comment]
This is the way we did it after inspiration from @tricoder42 snippet.

```
import ReactClickOutside from 'react-onclickoutside'
import React from 'react'

export default function create({onClickOutside}) {
  return ReactClickOutside(React.createClass({
    handleClickOutside(eventData) {
      onClickOutside(eventData)
    },
    render() {
      return this.props.children
    },
    propTypes: {
      children: React.PropTypes.isRequired
    }
  }))
}
```

We use a factory `create` function in basically all our files to avoid polluting react wih non-react stuff.
It's currently used like this (work in progress):
```
export default function create({
  React,
  StyleSheet,
  ClickOutside,
  css,
  styles,
  label,
  inputWidth,
  renders: {
    ButtonOk,
    ButtonCancel,
    Loader,
    Overlay,
    ToolTipSave,
    ToolTipCancel
  },
  triggers: {
    focus,
    blur,
    setUiValue
  }
}) {
  function onClickOutside() {
    blur()
  }

  function onFocus() {
    focus()
  }

  const style = StyleSheet.create(styles.toJS())
  const ClickOutsideElement = ClickOutside({onClickOutside})

  function render({state}) {
    return (
      <div className={css(style.ajaxInputContainer)}>

        <label className={css(style.ajaxLabel)}>{label}</label>
        // TODO: Gren fix this shit.
        {state.get('focus')}
        <ClickOutsideElement>
          <div className={css(style.ajaxInputWrapper)}>
            <input
              value={state.getIn(['inputUi', 'value'])}
              className={css(style.ajaxInput)}
              onChange={(domEvent) => setUiValue({
                value: domEvent.target.value
              })}
              onFocus={onFocus}
              style={{width: inputWidth}}
            />
            <div className={`${css(style.controls)} controls`}>
              <ToolTipCancel>
                <ButtonCancel tabIndex="-1"/>
              </ToolTipCancel>
              <ToolTipSave>
                <ButtonOk tabIndex="-1"/>
              </ToolTipSave>
            </div>
            <div style={{
              display: `${state.get('pending') ? 'block' : 'none'}`
            }}>
              <Overlay>
                <Loader />
              </Overlay>
            </div>
          </div>
        </ClickOutsideElement>
      </div>
    )
  }

  render.propTypes = {
    state: React.PropTypes.object.isRequired
  }
  return render
}
```
It's some stuff left to do, but it worked perfectly.

Overkill example, but didn't have the energy to go through the code, so might as well paste it as a whole.

Basically, I think documenting how you can convert to pure render is better than just offering to use props :-)

**Comment by davishmcclurg** [comment]
I tried the latest version with a stateless component and got this error:

> Warning: Stateless function components cannot be given refs (See ref "instance" in MyComponent created by OnClickOutside(MyComponent)). Attempts to access this ref will fail

Followed by:

> Uncaught TypeError: Cannot read property 'handleClickOutside' of null

**Comment by Pomax** [comment]
Hm, this sounds like it needs a new issue filed, specifically to check whether the HOC is wrapping a true component, or just a stateless render function. Want to file one?

**Comment by davishmcclurg** [comment]
@Pomax no problem, here's the new issue: https://github.com/Pomax/react-onclickoutside/issues/127
